image: rocker/geospatial:4.3.2

variables:
  GIT_DEPTH: 10
  R_LIBS_USER: "ci/lib"

cache:
  paths:
    - ${R_LIBS_USER}

stages:
  - install
  - check
  - deploy_shinyapps_io
  - test
  - pkgdown
  - pkgdown-move
  - deploy

install:
  stage: install
  script:
    - lsb_release -c
    - R -e "sessionInfo()"
    - if [[ $CI_DEFAULT_BRANCH == "master" || $CI_DEFAULT_BRANCH = "main" ]]; then echo "OK - Default branch is master or main"; else echo "Default branch is not master or main; please add yours ($CI_DEFAULT_BRANCH) where needed, as well as in the present line of code" ; exit 1; fi
    - echo "Library path for packages :" $R_LIBS_USER
    - mkdir -p $R_LIBS_USER
    - bash dev/ci/set_repos_option_to_match_thinkr_dev_env.sh
    - Rscript -e 'install.packages("pak")'
    - Rscript -e 'pak::local_install(upgrade = FALSE, dependencies = TRUE)'
  cache:
    key: ${CI_COMMIT_REF_SLUG}-dependencies
    paths:
      - ${R_LIBS_USER}
  artifacts:
    paths:
      - install
    expire_in: 30 days

check:
  stage: check
  script:
    - R -e 'rcmdcheck::rcmdcheck(args = c("--no-manual"), error_on = "warning", check_dir = "check")'
  cache:
    key: ${CI_COMMIT_REF_SLUG}-dependencies
    paths:
      - ${R_LIBS_USER}
  artifacts:
    paths:
      - check
    expire_in: 30 days

deploy_app:
  stage: deploy_shinyapps_io
  only:
    - main
    - uat
    - production
    - test-ci
  script:
    - Rscript dev/deploy_app.R
  cache:
    key: ${CI_COMMIT_REF_SLUG}-dependencies
    paths:
      - ${R_LIBS_USER}
  artifacts:
    paths:
      - deploy_app
    expire_in: 30 days

coverage:
  stage: test
  allow_failure: true
  when: on_success
  only:
    - main
    - master
    - uat
    - production
    - test-ci
  script:
    - bash dev/ci/set_repos_option_to_match_thinkr_dev_env.sh
    - Rscript -e 'pak::pkg_install(c("covr", "DT"), upgrade = FALSE)'
    - Rscript -e 'covr::gitlab(quiet = FALSE)'
  coverage: '/Coverage: \d+\.\d+/'
  cache:
    key: ${CI_COMMIT_REF_SLUG}-dependencies
    paths:
      - ${R_LIBS_USER}
  artifacts:
    paths:
      - public
    expire_in: 30 days

integration:
  stage: pkgdown
  allow_failure: true
  when: on_success
  only:
    - main
    - master
    - uat
    - production
    - test-ci
  script:
    - bash dev/ci/set_repos_option_to_match_thinkr_dev_env.sh
    - Rscript -e "pak::repo_add(universe = 'https://thinkr-open.r-universe.dev'); pak::pkg_install('thinkrtemplate')"
    - Rscript -e 'pak::pkg_install("pkgdown", upgrade = FALSE)'
    - Rscript -e 'pkgdown::build_site()'
  cache:
    key: ${CI_COMMIT_REF_SLUG}-dependencies
    paths:
      - ${R_LIBS_USER}
  artifacts:
    paths:
      - docs
    expire_in: 30 days

integration-test:
  stage: pkgdown-move
  dependencies:
    - integration
  only:
    - test-ci
  script:
    - mkdir -p public/test
    - 'curl --location --output artifacts.zip --header "JOB-TOKEN: $CI_JOB_TOKEN" "$CI_API_V4_URL/projects/$CI_PROJECT_ID/jobs/artifacts/$CI_DEFAULT_BRANCH/download?job=pages" &&
      unzip artifacts.zip &&
      rm artifacts.zip &&
      echo "copied $CI_DEFAULT_BRANCH artifacts" ||
      echo "copied $CI_DEFAULT_BRANCH artifacts failed"'
    - 'curl --location --output artifacts.zip --header "JOB-TOKEN: $CI_JOB_TOKEN" "$CI_API_V4_URL/projects/$CI_PROJECT_ID/jobs/artifacts/production/download?job=pages" &&
      unzip artifacts.zip &&
      rm artifacts.zip &&
      echo "copied production artifacts" ||
      echo "copied production artifacts failed"'
    - cp -r docs/* public/test
  artifacts:
    paths:
      - public
    expire_in: 30 days

integration-production:
  stage: pkgdown-move
  dependencies:
    - integration
  only:
    - production
  script:
    - mkdir -p public/production
    - 'curl --location --output artifacts.zip --header "JOB-TOKEN: $CI_JOB_TOKEN" "$CI_API_V4_URL/projects/$CI_PROJECT_ID/jobs/artifacts/$CI_DEFAULT_BRANCH/download?job=pages" &&
      unzip artifacts.zip &&
      rm artifacts.zip &&
      echo "copied $CI_DEFAULT_BRANCH artifacts" ||
      echo "copied $CI_DEFAULT_BRANCH artifacts failed"'
    - cp -r docs/* public/production
  artifacts:
    paths:
      - public
    expire_in: 30 days

integration-uat:
  stage: pkgdown-move
  dependencies:
    - integration
  only:
    - uat
  script:
    - mkdir -p public
    - 'curl --location --output artifacts.zip --header "JOB-TOKEN: $CI_JOB_TOKEN" "$CI_API_V4_URL/projects/$CI_PROJECT_ID/jobs/artifacts/uat/download?job=pages" &&
      unzip artifacts.zip &&
      rm artifacts.zip &&
      echo "copied production artifacts" ||
      echo "copied production artifacts failed"'
    - cp -r docs/* public
  artifacts:
    paths:
      - public
    expire_in: 30 days

integration-main:
  stage: pkgdown-move
  dependencies:
    - integration
  only:
    - main
    - master
  script:
    - mkdir -p public
    - 'curl --location --output artifacts.zip --header "JOB-TOKEN: $CI_JOB_TOKEN" "$CI_API_V4_URL/projects/$CI_PROJECT_ID/jobs/artifacts/production/download?job=pages" &&
      unzip artifacts.zip &&
      rm artifacts.zip &&
      echo "copied production artifacts" ||
      echo "copied production artifacts failed"'
    - cp -r docs/* public
  artifacts:
    paths:
      - public
    expire_in: 30 days

pages:
  stage: deploy
  script:
    - echo "deployment with cache"
  artifacts:
    paths:
      - public
  only:
    - main
    - master
    - uat
    - production
    - test-ci
