flat_map.Rmd:
  path: dev/flat_map.Rmd
  state: active
  R:
  - R/draw_map_focus_one_project.R
  - R/draw_map_selected_projects.R
  tests:
  - tests/testthat/test-draw_map_selected_projects.R
  - tests/testthat/test-draw_map_focus_one_project.R
  vignettes: vignettes/draw-the-switzerland-maps-with-projects.Rmd
  inflate:
    flat_file: dev/flat_map.Rmd
    vignette_name: Draw the Switzerland maps with projects
    open_vignette: true
    check: false
    document: true
    overwrite: 'yes'
flat_map_subfunctions.Rmd:
  path: dev/flat_map_subfunctions.Rmd
  state: active
  R:
  - R/map_utils.R
  - R/draw_map_base.R
  tests:
  - tests/testthat/test-map_utils.R
  - tests/testthat/test-draw_map_base.R
  vignettes: []
  inflate:
    flat_file: dev/flat_map_subfunctions.Rmd
    vignette_name: .na
    open_vignette: true
    check: false
    document: true
    overwrite: 'yes'
flat_prepare_data.Rmd:
  path: dev/flat_prepare_data.Rmd
  state: active
  R: R/prepare_projects_data.R
  tests: tests/testthat/test-prepare_projects_data.R
  vignettes: vignettes/prepare-update-data-used-by-the-app.Rmd
  inflate:
    flat_file: dev/flat_prepare_data.Rmd
    vignette_name: Prepare/update data used by the app
    open_vignette: true
    check: false
    document: true
    overwrite: 'yes'
flat_prepare_data_subfunctions.Rmd:
  path: dev/flat_prepare_data_subfunctions.Rmd
  state: active
  R:
  - R/add_col_raw_data.R
  - R/clean_raw_data.R
  - R/get_canton_main_resp_orga.R
  - R/get_coord_main_resp_orga.R
  - R/get_id_cantons_influenced.R
  - R/get_nb_cantons_influenced.R
  - R/get_prop_budget.R
  - R/import_raw_data.R
  - R/save_projects_data.R
  - R/translate_values_in_data.R
  tests:
  - tests/testthat/test-import_raw_data.R
  - tests/testthat/test-add_col_raw_data.R
  - tests/testthat/test-clean_raw_data.R
  - tests/testthat/test-get_coord_main_resp_orga.R
  - tests/testthat/test-get_canton_main_resp_orga.R
  - tests/testthat/test-get_id_cantons_influenced.R
  - tests/testthat/test-get_nb_cantons_influenced.R
  - tests/testthat/test-get_prop_budget.R
  - tests/testthat/test-translate_values_in_data.R
  - tests/testthat/test-save_projects_data.R
  vignettes: []
  inflate:
    flat_file: dev/flat_prepare_data_subfunctions.Rmd
    vignette_name: .na
    open_vignette: true
    check: false
    document: true
    overwrite: ask
