flat_doc_deploy_app.Rmd:
  path: dev/flat_doc_deploy_app.Rmd
  state: active
  R: []
  tests: []
  vignettes: vignettes/deploy-the-app.Rmd
  inflate:
    flat_file: dev/flat_doc_deploy_app.Rmd
    vignette_name: Deploy the app
    open_vignette: true
    check: false
    document: true
    overwrite: 'yes'
flat_doc_general_overview.Rmd:
  path: dev/flat_doc_general_overview.Rmd
  state: active
  R: []
  tests: []
  vignettes: vignettes/general-overview-of-the-app.Rmd
  inflate:
    flat_file: dev/flat_doc_general_overview.Rmd
    vignette_name: General overview of the app
    open_vignette: true
    check: false
    document: true
    overwrite: 'yes'
flat_fct_utils.Rmd:
  path: dev/flat_fct_utils.Rmd
  state: active
  R:
  - R/clean_id_project.R
  - R/create_skeleton_dic.R
  - R/get_back_arrow_html.R
  - R/get_trad_title.R
  - R/languageswitchinput.R
  - R/fct_utils.R
  tests:
  - tests/testthat/test-fct_utils.R
  - tests/testthat/test-get_trad_title.R
  - tests/testthat/test-clean_id_project.R
  - tests/testthat/test-languageswitchinput.R
  - tests/testthat/test-create_skeleton_dic.R
  - tests/testthat/test-get_back_arrow_html.R
  vignettes: []
  inflate:
    flat_file: dev/flat_fct_utils.Rmd
    vignette_name: .na
    open_vignette: true
    check: false
    document: true
    overwrite: 'yes'
flat_filter_project_data.Rmd:
  path: dev/flat_filter_project_data.Rmd
  state: active
  R:
  - R/filter_projects_data.R
  - R/get_budget_range.R
  - R/get_cantons_main_org.R
  - R/get_input_data_to_display.R
  - R/get_pi1_to_display.R
  - R/get_pi2_to_display.R
  - R/get_prop_self_funded_range.R
  - R/get_topics_to_display.R
  - R/load_projects_data.R
  tests:
  - tests/testthat/test-load_projects_data.R
  - tests/testthat/test-filter_projects_data.R
  - tests/testthat/test-get_input_data_to_display.R
  - tests/testthat/test-get_topics_to_display.R
  - tests/testthat/test-get_pi1_to_display.R
  - tests/testthat/test-get_pi2_to_display.R
  - tests/testthat/test-get_budget_range.R
  - tests/testthat/test-get_prop_self_funded_range.R
  - tests/testthat/test-get_cantons_main_org.R
  vignettes: []
  inflate:
    flat_file: dev/flat_filter_project_data.Rmd
    vignette_name: .na
    open_vignette: true
    check: false
    document: true
    overwrite: 'yes'
flat_map.Rmd:
  path: dev/flat_map.Rmd
  state: active
  R:
  - R/draw_map_focus_one_project.R
  - R/draw_map_selected_projects.R
  tests:
  - tests/testthat/test-draw_map_selected_projects.R
  - tests/testthat/test-draw_map_focus_one_project.R
  vignettes: vignettes/draw-the-switzerland-maps-with-projects.Rmd
  inflate:
    flat_file: dev/flat_map.Rmd
    vignette_name: Draw the Switzerland maps with projects
    open_vignette: true
    check: false
    document: true
    overwrite: 'yes'
flat_map_subfunctions.Rmd:
  path: dev/flat_map_subfunctions.Rmd
  state: active
  R:
  - R/map_utils.R
  - R/draw_map_base.R
  - R/get_influence_project.R
  tests:
  - tests/testthat/test-map_utils.R
  - tests/testthat/test-draw_map_base.R
  - tests/testthat/test-get_influence_project.R
  vignettes: []
  inflate:
    flat_file: dev/flat_map_subfunctions.Rmd
    vignette_name: .na
    open_vignette: true
    check: false
    document: true
    overwrite: 'yes'
flat_plot_budget.Rmd:
  path: dev/flat_plot_budget.Rmd
  state: active
  R: R/plot_contrib_budget_highcharter.R
  tests: tests/testthat/test-plot_contrib_budget_highcharter.R
  vignettes: vignettes/draw-the-distribution-of-contributions.Rmd
  inflate:
    flat_file: dev/flat_plot_budget.Rmd
    vignette_name: Draw the distribution of contributions
    open_vignette: false
    check: false
    document: true
    overwrite: 'yes'
flat_plot_budget_subfunctions.Rmd:
  path: dev/flat_plot_budget_subfunctions.Rmd
  state: active
  R: R/get_data_repart_budget_one_project.R
  tests: tests/testthat/test-get_data_repart_budget_one_project.R
  vignettes: []
  inflate:
    flat_file: dev/flat_plot_budget_subfunctions.Rmd
    vignette_name: .na
    open_vignette: false
    check: false
    document: true
    overwrite: 'yes'
flat_prepare_data.Rmd:
  path: dev/flat_prepare_data.Rmd
  state: active
  R: R/prepare_projects_data.R
  tests: tests/testthat/test-prepare_projects_data.R
  vignettes: vignettes/prepare-update-data-used-by-the-app.Rmd
  inflate:
    flat_file: dev/flat_prepare_data.Rmd
    vignette_name: Prepare/update data used by the app
    open_vignette: true
    check: false
    document: true
    overwrite: 'yes'
flat_prepare_data_subfunctions.Rmd:
  path: dev/flat_prepare_data_subfunctions.Rmd
  state: active
  R:
  - R/add_col_raw_data.R
  - R/clean_raw_data.R
  - R/get_canton_main_resp_orga.R
  - R/get_coord_main_resp_orga.R
  - R/get_id_cantons_influenced.R
  - R/get_nb_cantons_influenced.R
  - R/get_prop_budget.R
  - R/import_raw_data.R
  - R/prepare_one_project_card.R
  - R/prepare_projects_cards.R
  - R/prepare_projects_data.R
  - R/save_projects_data.R
  - R/translate_values_in_data.R
  tests:
  - tests/testthat/test-import_raw_data.R
  - tests/testthat/test-add_col_raw_data.R
  - tests/testthat/test-clean_raw_data.R
  - tests/testthat/test-get_coord_main_resp_orga.R
  - tests/testthat/test-get_canton_main_resp_orga.R
  - tests/testthat/test-get_id_cantons_influenced.R
  - tests/testthat/test-get_nb_cantons_influenced.R
  - tests/testthat/test-get_prop_budget.R
  - tests/testthat/test-translate_values_in_data.R
  - tests/testthat/test-save_projects_data.R
  - tests/testthat/test-prepare_projects_data.R
  - tests/testthat/test-prepare_one_project_card.R
  - tests/testthat/test-prepare_projects_cards.R
  vignettes: []
  inflate:
    flat_file: dev/flat_prepare_data_subfunctions.Rmd
    vignette_name: .na
    open_vignette: true
    check: false
    document: true
    overwrite: ask
