---
title: "flat_map.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
library(sf)
library(leaflet)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```



# Map utils

  
```{r function-map-utils}
#' @filename map_utils
#' @importFrom sf st_union st_centroid st_geometry
#' @importFrom stats setNames 
#' @noRd
compute_switzerland_centroid  <- function() {
  read_cantons_sf() |> 
    st_union() |> 
    st_centroid() |> 
    st_geometry() |> 
    unlist() |> 
    setNames(
      c("lng", "lat")
    )
}

#' @filename map_utils
#' @importFrom sf st_bbox
#' @noRd
compute_switzerland_bounding_box <- function() {
  bounding_box <- read_cantons_sf() |> 
    st_bbox()
  attr(bounding_box, "crs") <- NULL
  attr(bounding_box, "class") <- NULL
  return(bounding_box)
}

#' @filename map_utils
#' @noRd
get_switzerland_centroid <- function() {
  # Generated via compute_switzerland_centroid() |> dput()
  c(
    lng = 8.22730129708567, 
    lat = 46.8019720665898
  )
}

#' @filename map_utils
#' @noRd
get_switzerland_bounding_box <- function() {
  # Generated via compute_switzerland_bounding_box() |> dput()
  c(
    xmin = 5.9561,
    ymin = 45.8171,
    xmax = 10.4948,
    ymax = 47.8085
  )
}

#' Generate dummy project data
#' @return A sf data.frame
#' @importFrom sf st_as_sf
#' @filename map_utils
#' @noRd
dummy_project_data_sf <- function() { 
  data.frame(
    short_title = "PSCH",
    addr = "52 Avenue de la Gare, 1003 Lausanne, Switzerland",
    lat = 46.51756965,
    long = 6.63061493418584
  ) |>
    st_as_sf(
      coords = c("long", "lat"),
      crs = 4326
    )
}
```


```{r tests-map-utils}
test_that("Switzerland centroid are coherent between computation and accessor function", {
  expect_equal(
    compute_switzerland_centroid(),
    get_switzerland_centroid()
  )
})

test_that("Switzerland bounding box are coherent between computation and accessor function", {
  expect_equal(
    compute_switzerland_bounding_box(),
    get_switzerland_bounding_box()
  )
})
```



# Draw leaflet map


```{r function-map}
#' Draw main interactive map
#'
#' @param projects_data_sf A sf data.frame containing coordinates of project 
#' main organisation and project `short_title`.
#' 
#' @param zoom_level An integer. The zoom level for the map. Defines
#' default zoom level.
#' 
#' @return A leaflet object.
#' 
#' @importFrom leaflet leaflet setView addProviderTiles leafletOptions setMaxBounds
#' 
#' @filename map
#' @noRd
draw_map_base <- function(zoom_level = 8) {
  
  switzerland_centroid <- get_switzerland_centroid()
  switzerland_bounding_box <- get_switzerland_bounding_box()
  
  leaflet(
    options = leafletOptions(minZoom = zoom_level)
  ) |>
    addProviderTiles(
      provider = "CartoDB.Positron"
      ) |>
    setView(
      lng = switzerland_centroid[["lng"]],
      lat = switzerland_centroid[["lat"]],
      zoom = zoom_level
    ) |> 
    setMaxBounds(
      lng1 = switzerland_bounding_box[["xmin"]],
      lat1 = switzerland_bounding_box[["ymin"]],
      lng2 = switzerland_bounding_box[["xmax"]],
      lat2 = switzerland_bounding_box[["ymax"]]
    )
}
```

```{r examples-map}
draw_map_base() 
```

```{r tests-map}
test_that("draw_map_base() returns a leaflet object", {
  expect_s3_class(
    draw_map_base(),
    c("leaflet", "htmlwidget")
  )
})
```

# Draw map of selected projects
    
```{r function-draw_map_selected_projects}
#' Draw map of selected projects
#' 
#' @param projects_data_sf A sf data.frame containing coordinates of project 
#' main organisation and project `short_title`.
#' 
#' @inheritParams draw_map_base
#' 
#' @return A leaflet object.
#' 
#' @importFrom leaflet addCircleMarkers  addPolygons
#' 
#' @filename map
#' @noRd 
draw_map_selected_projects <- function(
    projects_data_sf,
    zoom_level = 8
){
  draw_map_base(zoom_level) |> 
    addPolygons(
      data = read_cantons_sf(),
      weight = 1,
      color = psch_blue(),
      fillColor = psch_blue(),
      fillOpacity = 0.3
    ) |>
    addCircleMarkers(
      data = projects_data_sf,
      color = psch_orange(),
      stroke = FALSE,
      fillOpacity = 0.8,
      label = ~ as.character(short_title)
    )
}
```
  
```{r example-draw_map_selected_projects}
draw_map_selected_projects(
  projects_data_sf = dummy_project_data_sf()
)
```
  
```{r tests-draw_map_selected_projects}
test_that("draw_map_selected_projects() returns a leaflet object", {
  expect_s3_class(
    draw_map_selected_projects(
      projects_data_sf = dummy_project_data_sf()
    ),
    c("leaflet", "htmlwidget")
  )
})
```
  
  
# Draw map focused on one project
    
```{r function-draw_map_focus_one_project}
#' Draw map of selected projects
#' 
#' @param projects_data_sf A sf data.frame containing coordinates of project 
#' main organisation and project `short_title`.
#' @param project_short_title Character. Id of the project.
#' 
#' @return A leaflet object.
#' 
#' @importFrom leaflet addCircleMarkers  addPolygons
#' 
#' @filename map
#' @noRd 
draw_map_focus_one_project <- function(
    projects_data_sf = readRDS(system.file("data-projects", "projects_de.rds", package = "observatoire")),
    project_short_title = "1+1=3  PGV03.038"
){

  cantons_sf <- read_cantons_sf()
  
  # Extract target cantons from project_data_sf
  project_data_sf <- projects_data_sf |> 
    filter(short_title == project_short_title) |> 
    select(short_title, geometry, geo_range) |> 
    mutate(
      geo_range = 
        str_remove_all(
          geo_range, 
          "\r|\n"
        )
    ) |> 
    mutate(
      geo_range = 
        str_split(
          geo_range, 
          pattern = ","
        )
    ) |>
    unnest(geo_range)
    
  
  
  # Add column target_cantons (TRUE/FALSE) in project_data_sf
  
  draw_map_base()
  
  # Display target cantons in psch orange / others psch blue
  # Display selected project in psch orange
  
  # Nice to have
  # Display lines radiating from project to centroid of target cantons
  
}
```
  
```{r example-draw_map_focus_one_project}
# Modify dummy_project_data_sf() to include target cantons
draw_map_focus_one_project(
  projects_data_sf = dummy_project_data_sf()
)
```
  
```{r tests-draw_map_focus_one_project}
test_that("draw_map_focus_one_project works", {
  expect_s3_class(
    draw_map_selected_projects(
      projects_data_sf = dummy_project_data_sf()
    ),
    c("leaflet", "htmlwidget")
  )
})
```
  


```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(
  flat_file = "dev/flat_map.Rmd", 
  vignette_name = NA,
  check = FALSE,
  overwrite = TRUE
)
```

