---
title: "flat_fct_utils.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

# Read cantons spatial data

```{r function-read_cantons_sf}
#' Read cantons polygons data
#' @importFrom sf st_read
#' @filename fct_utils
#' @noRd
read_cantons_sf <- function() {
  st_read(
    dsn = system.file(
      "data-geo",
      "gadm41_CHE_1.json", 
      package = "observatoire"
    ),
    quiet = TRUE
  )
}
```

```{r tests-read_cantons_sf}
test_that("read_cantons_sf works", {
  cantons_sf <- read_cantons_sf()
  
  expect_equal(
    colnames(cantons_sf),
    c(
      "GID_1",
      "GID_0",
      "COUNTRY",
      "NAME_1",
      "VARNAME_1",
      "NL_NAME_1",
      "TYPE_1",
      "ENGTYPE_1",
      "CC_1",
      "HASC_1",
      "ISO_1",
      "geometry"
    )
  )
  
  expect_equal(
    dim(cantons_sf),
    c(26L, 12L)
  )
  
  expect_s3_class(
    cantons_sf,
    c("sf", "data.frame")
  )
  
})
```

# Read projects data

```{r function-read_projects_data}
#' Read projects data
#' @importFrom glue glue
#' @filename fct_utils
#' @noRd
read_projects_data <- function(
    language = c("de", "fr")
    ){
  
  language <- match.arg(language)
  
  readRDS(
    system.file(
      "data-projects", 
      glue("projects_{language}.rds"),
      package = "observatoire"
    )
  )
    
}
```
  
```{r tests-read_projects_data}
test_that("Test that the reading of projects data works", {
  
  expect_error(
    data_projects_fr <- read_projects_data(
      language = "fr"
    ), 
    regexp = NA
  )
  
  expect_true(
    inherits(data_projects_fr, "data.frame")
  )
  
   expect_error(
    data_projects_de <- read_projects_data(
      language = "de"
    ), 
    regexp = NA
  )
  
  expect_true(
    inherits(data_projects_de, "data.frame")
  )
  
  
})
```
  

# Get PSCH colors

```{r function-colors}
#' @filename fct_utils
#' @noRd
psch_blue <- function() {
  # Meerblau
  "#578397"
} 

#' @filename fct_utils
#' @noRd
psch_orange <- function() {
  # Corporate: Orange
  "#f59300"
}

#' @filename fct_utils
#' @noRd
psch_yellow <- function() {
  # BGM: Gelb
  "#fbbc00"
}

#' @filename fct_utils
#' @noRd
psch_bronce <- function() {
  # Bronce
  "#695b2e"
}

#' @filename fct_utils
#' @noRd
psch_green <- function() {
  # Lindengrün
  "#b1c000"
}
```

```{r tests-colors}
test_that("psch color function return proper color",{
  expect_equal(
    psch_blue(),
    "#578397"
  )
  expect_equal(
    psch_orange(),
    "#f59300"
  )
})
```

# Get the translation of a title
    
```{r function-get_trad_title}
#' Get the translation of a title
#' 
#' @param title_id Character. Id of the title in the dictionary.
#' @param language Character. Language ("de" or "fr").
#' @param dic_titles_pages Tibble. Title of the pages dictionaries. Mainly used for examples and unit testing purpose.
#' 
#' @importFrom readr read_csv2 locale
#' @importFrom dplyr filter pull 
#' 
#' @return A character. Translation. 
#' 
#' @noRd
get_trad_title <- function(
    title_id,
    language, 
    dic_titles_pages = NULL
    ) {
  
  if (is.null(dic_titles_pages)) {
    dic_titles_pages <- read_csv2(
      app_sys("data-dic",
              "dic_titles_app.csv"),
      show_col_types = FALSE,
      locale = locale(decimal_mark = ",", grouping_mark = ".")
    )
  }
  
  dic_titles_pages |> 
    filter(id == title_id) |> 
    pull(language)
  
}
```
  
```{r example-get_trad_title}
data("toy_dic_titles_pages")

get_trad_title(
  title_id = "project_start_year_title",
  language = "fr", 
  dic_titles_pages = toy_dic_titles_pages
)

get_trad_title(
  title_id = "project_start_year_title",
  language = "de", 
  dic_titles_pages = toy_dic_titles_pages
)
```
  
```{r tests-get_trad_title}
test_that("Test that the translation of a title works", {
  
  data("toy_dic_titles_pages")

  expect_equal(
    object = get_trad_title(
      title_id = "project_start_year_title",
      language = "fr", 
      dic_titles_pages = toy_dic_titles_pages
    ),
    expected = "Année de lancement"
  )
  
  expect_equal(
    object = get_trad_title(
      title_id = "project_start_year_title",
      language = "de", 
      dic_titles_pages = toy_dic_titles_pages
    ),
    expected = "Projektstart"
  )

})
```
  
# Clean the id of a project

```{r function-clean_id_project}
#' Clean the id of a project
#' 
#' @return Character. The id cleaned.
#' 
#' @noRd
clean_id_project <- function(
    id_project
    ){
  
    iconv(
      gsub("[[:punct:]]| ", "", id_project), 
      to = "ASCII//TRANSLIT"
    )
  
}
```
  
```{r tests-clean_id_project}
test_that("Test that the cleaning of the id of a project works", {
  
  expect_equal(
    object = clean_id_project(
      id_project = "FM_ProPCC+"
    ), 
    expected = "FMProPCC"
  )
  
  expect_equal(
    object = clean_id_project(
      id_project = "Sturzprävention/ in der Spitex"
    ), 
    expected = "SturzpraventioninderSpitex"
  )

})
```
  
# Create a custom toggl switch for the language 
    
```{r function-languageSwitchInput}
#' Create a custom toggl switch for the language 
#' 
#' @param inputId Character. InputId
#' @param label Character. label
#' @param values Character. values
#' @param selected Character. selected
#' 
#' @return A shiny input
#' 
#' @noRd
languageSwitchInput <- function(inputId, label, values, selected) {
  tags$div(
    id = inputId,
    class = "switch-container",
    tags$span(class = "switch-label", label),
    tags$span(class = "switch-label", values[1]),
    tags$label(
      class = "switch",
      tags$input(type = "checkbox", id = inputId, value = selected),
      tags$span(class = "slider")
    ),
    tags$span(class = "switch-label", values[2])
  )
  
}
```
  
```{r example-languageSwitchInput}
```
  
```{r tests-languageSwitchInput}
test_that("languageSwitchInput works", {
  expect_true(inherits(languageSwitchInput, "function")) 
})
```
  
```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(
  flat_file = "dev/flat_fct_utils.Rmd", 
  vignette_name = NA,
  check = FALSE,
  overwrite = TRUE
)
```

