---
title: "Draw maps - subfunctions"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
library(sf)
library(leaflet)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

# Map utils

```{r function-map-utils}
#' @importFrom sf st_union st_centroid st_geometry
#' @importFrom stats setNames 
#' @noRd
compute_switzerland_centroid  <- function() {
  read_cantons_sf() |> 
    st_union() |> 
    st_centroid() |> 
    st_geometry() |> 
    unlist() |> 
    setNames(
      c("lng", "lat")
    )
}

#' @filename map_utils
#' @importFrom sf st_bbox
#' @noRd
compute_switzerland_bounding_box <- function() {
  bounding_box <- read_cantons_sf() |> 
    st_bbox()
  attr(bounding_box, "crs") <- NULL
  attr(bounding_box, "class") <- NULL
  return(bounding_box)
}

#' @filename map_utils
#' @noRd
get_switzerland_centroid <- function() {
  # Generated via compute_switzerland_centroid() |> dput()
  c(
    lng = 8.22730129708567, 
    lat = 46.8019720665898
  )
}

#' @filename map_utils
#' @noRd
get_switzerland_bounding_box <- function() {
  # Generated via compute_switzerland_bounding_box() |> dput()
  c(
    xmin = 5.9561,
    ymin = 45.8171,
    xmax = 10.4948,
    ymax = 47.8085
  )
}

#' Generate dummy project data
#' @return A sf data.frame
#' @importFrom sf st_as_sf
#' @filename map_utils
#' @noRd
dummy_project_data_sf <- function() { 
  data.frame(
    short_title = "PSCH",
    addr = "52 Avenue de la Gare, 1003 Lausanne, Switzerland",
    lat = 46.51756965,
    long = 6.63061493418584
  ) |>
    st_as_sf(
      coords = c("long", "lat"),
      crs = 4326
    )
}
```

```{r tests-map-utils}
test_that("Switzerland centroid are coherent between computation and accessor function", {
  expect_equal(
    compute_switzerland_centroid(),
    get_switzerland_centroid()
  )
})

test_that("Switzerland bounding box are coherent between computation and accessor function", {
  expect_equal(
    compute_switzerland_bounding_box(),
    get_switzerland_bounding_box()
  )
})
```

# Draw leaflet map

```{r function-map}
#' Draw main interactive map
#'
#' @param projects_data_sf A sf data.frame containing coordinates of project 
#' main organisation and project `short_title`.
#' 
#' @param zoom_level An integer. The zoom level for the map. Defines
#' default zoom level.
#' 
#' @return A leaflet object.
#' 
#' @importFrom leaflet leaflet setView addProviderTiles leafletOptions setMaxBounds
#' 
#' @noRd
draw_map_base <- function(zoom_level = 8) {
  
  switzerland_centroid <- get_switzerland_centroid()
  switzerland_bounding_box <- get_switzerland_bounding_box()
  
  leaflet(
    options = leafletOptions(minZoom = zoom_level)
  ) |>
    addProviderTiles(
      provider = "CartoDB.Positron"
      ) |>
    setView(
      lng = switzerland_centroid[["lng"]],
      lat = switzerland_centroid[["lat"]],
      zoom = zoom_level
    ) |> 
    setMaxBounds(
      lng1 = switzerland_bounding_box[["xmin"]],
      lat1 = switzerland_bounding_box[["ymin"]],
      lng2 = switzerland_bounding_box[["xmax"]],
      lat2 = switzerland_bounding_box[["ymax"]]
    )
}
```

```{r examples-map}
draw_map_base() 
```

```{r tests-map}
test_that("draw_map_base() returns a leaflet object", {
  expect_s3_class(
    draw_map_base(),
    c("leaflet", "htmlwidget")
  )
})
```
 
# Get the geo influence elements of a project
    
```{r function-get_influence_project}
#' Get the geo influence elements of a project
#' 
#' @param projects_data_sf A sf data.frame containing coordinates of project 
#' main organisation and project `short_title`.
#' @param id_project Character. Id of the project.
#' @param cantons_sf Sf data. Cantons geometry. Mainly used for examples and unit testing purpose.
#' 
#' @importFrom dplyr filter select left_join mutate rename
#' @importFrom sf st_drop_geometry st_centroid st_union st_cast
#' @importFrom tidyr separate_rows
#' 
#' @return A list with 3 elements. The coord of the projetc, the polygons of the cantons and the info influenced/not influenced, the lines between the point anf the center of gravity of the cantons influenced.
#' 
#' @noRd
get_influence_project <- function(
    projects_data_sf,
    id_project,
    cantons_sf = NULL
    ){
    
  # Create a coord_sf_project object
  projects_data_sf_filtered <- projects_data_sf |> 
    filter(short_title == id_project) 
  
  coord_sf_project <- projects_data_sf_filtered |> 
    select(short_title, geometry)
  
  # Extract target cantons from project_data_sf
  project_data_cantons_sf <- projects_data_sf_filtered |> 
    st_drop_geometry() |> 
    select(short_title, geo_range_id) |> 
    separate_rows(
      geo_range_id, 
      sep = ", "
    )
  
  # Create a cantons_sf_project object with column target_cantons (TRUE/FALSE)
  cantons_sf_project <- left_join(
    x = cantons_sf |> 
      select(HASC_1, NAME_1, geometry),
    y = project_data_cantons_sf |> 
      rename(HASC_1 = geo_range_id), 
    by = "HASC_1"
  ) |> 
    mutate(
      target_cantons = ifelse(
        is.na(short_title),
        FALSE, 
        TRUE
      )
    ) |> 
    select(- short_title)
  
  # Add the lines from the centroid
  if (nrow(cantons_sf_project |>
           filter(target_cantons == TRUE)) > 0) {
    
    cantons_centroid <- cantons_sf_project |>
      filter(
        target_cantons == TRUE
      ) |>
      st_centroid() |>
      mutate(
        project = coord_sf_project$geometry
      )
    
    cantons_influenced_lines <- st_union(
      cantons_centroid$geometry,
      cantons_centroid$project
      ) |>
      st_cast("LINESTRING")
    
  } else {
    
    cantons_influenced_lines <- NULL
    
  }
  
  return(
    list(
      coord_sf_project = coord_sf_project,
      cantons_sf_project = cantons_sf_project,
      cantons_influenced_lines = cantons_influenced_lines
    )
  )
  
}
```
  
```{r example-get_influence_project}
data("toy_projects_data_sf")
data("toy_cantons_sf")

get_influence_project(
  projects_data_sf = toy_projects_data_sf,
  id_project = "1+1=3  PGV03.038", 
  cantons_sf = toy_cantons_sf
)
```
  
```{r tests-get_influence_project}
test_that("get_influence_project works", {
  
  data("toy_projects_data_sf")
  data("toy_cantons_sf")
  
  res_get_influence_project <- get_influence_project(
    projects_data_sf = toy_projects_data_sf,
    id_project = "1+1=3  PGV03.038",
    cantons_sf = toy_cantons_sf
  )
  
  expect_equal(
    object = names(res_get_influence_project),
    expected = c(
      "coord_sf_project", 
      "cantons_sf_project", 
      "cantons_influenced_lines"
    )
  )
  
  expect_true(
    inherits(res_get_influence_project$coord_sf_project, "sf")
  )
  
  expect_true(
    inherits(res_get_influence_project$cantons_sf_project, "sf")
  )
  
  expect_true(
    inherits(res_get_influence_project$cantons_influenced_lines, "sfc_LINESTRING")
  )
  
})
```
  

```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(
  flat_file = "dev/flat_map_subfunctions.Rmd", 
  vignette_name = NA,
  check = FALSE,
  overwrite = TRUE
)
```

