---
title: "Draw the distribution of contributions - subfunctions"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
library(purrr)
library(dplyr)
library(tidyr)
library(sf)
library(readr)
library(scales)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

# Get the data of the distribution of the budget for one project
    
```{r function-get_data_repart_budget_one_project}
#' Get the data of the distribution of the budget for one project
#' 
#' @param id_project Character. ID of the project, 'short_title' in data.
#' @param data_projects Tibble. Data projects.
#' @param language Character. Language, 'fr' or 'de'.
#' 
#' @importFrom dplyr filter select
#' @importFrom sf st_drop_geometry
#' @importFrom tibble tibble
#' @importFrom scales number
#' 
#' @return Tibble. Data to be plotted.
#' 
#' @noRd
get_data_repart_budget_one_project <- function(
    id_project,
    data_projects,
    language = c("de", "fr")) {
  
  # Filter the project
  data_this_project <- data_projects |> 
    filter(short_title == id_project) |> 
    st_drop_geometry()
  
  # Create the data
  data_repart <- tibble(
    name = c("gfch", "orga", "third")
  )
  
  data_repart$value <- round(
    data_this_project |> 
      select(
        "prop_budget_gfch", 
        "prop_budget_orga", 
        "prop_budget_third_party"
      ) |> unlist() * 100, 
    1)
  
  data_repart$value_tooltip <- data_this_project |> 
    select(
      "budget_gfch", 
      "budget_orga", 
      "budget_third_party"
    ) |> unlist() |> 
    number(
      suffix = " CHF"
    )
    
  # Translate the data
  if (language == "de") {
    
    data_repart$name <- c(
      "GFCH", 
      "Haupt-Org", 
      "Dritte"
    )
    
  } else if (language == "fr") {
    
    data_repart$name <- c(
      "PSCH", 
      "Organisation principale", 
      "Tiers"
    )
    
  }
  
  return(data_repart)
    
}
```
  
```{r example-get_data_repart_budget_one_project}
data("toy_projects_data_sf")

get_data_repart_budget_one_project(
  data_projects = toy_projects_data_sf,
  id_project = "1+1=3  PGV03.038",
  language = "de"
)

get_data_repart_budget_one_project(
  data_projects = toy_projects_data_sf,
  id_project = "1+1=3  PGV03.038",
  language = "fr"
)
```
  
```{r tests-get_data_repart_budget_one_project}
test_that("get_data_repart_budget_one_project works for FR data", {
  
  data("toy_projects_data_sf")

  data_repart_budget_one_proj_fr <- get_data_repart_budget_one_project(
    data_projects = toy_projects_data_sf,
    id_project = "1+1=3  PGV03.038",
    language = "fr"
  )
  
  expect_equal(
    object = data_repart_budget_one_proj_fr,
    expected = structure(
                 list(
                   name = c("PSCH", "Organisation principale", "Tiers"),
                   value = c(
                     prop_budget_gfch = 34.1,
                     prop_budget_orga = 4.3,
                     prop_budget_third_party = 61.7
                   ),
                   value_tooltip = c(
                     budget_gfch = "200 000 CHF",
                     budget_orga = "25 000 CHF",
                     budget_third_party = "361 720 CHF"
                   )
                 ),
                 row.names = c(NA, -3L),
                 class = c("tbl_df", "tbl", "data.frame")
               )
    )
  
  
})

test_that("get_data_repart_budget_one_project works for DE data", {
  
  data("toy_projects_data_sf")

  data_repart_budget_one_proj_de <- get_data_repart_budget_one_project(
    data_projects = toy_projects_data_sf,
    id_project = "1+1=3  PGV03.038",
    language = "de"
  )
  
  expect_equal(
    object = data_repart_budget_one_proj_de,
    expected = structure(
                 list(
                   name = c("GFCH", "Haupt-Org", "Dritte"),
                   value = c(
                     prop_budget_gfch = 34.1,
                     prop_budget_orga = 4.3,
                     prop_budget_third_party = 61.7
                   ),
                   value_tooltip = c(
                     budget_gfch = "200 000 CHF",
                     budget_orga = "25 000 CHF",
                     budget_third_party = "361 720 CHF"
                   )
                 ),
                 row.names = c(NA, -3L),
                 class = c("tbl_df", "tbl", "data.frame")
               )
  )

})
```
  
# Get budget data by theme for selected projects
    
```{r function-get_data_budget_by_theme_selected_projects}
#' Get budget data by theme for selected projects
#' 
#' @param projects_data_sf Tibble. Data projects.
#' @param language Character. Language, 'fr' or 'de'.
#' @param topic Character. A specific topic/theme in the form topic_
#' 
#' @return A tibble with three columns: `name`, `value` and `value_tooltip`
#' 
#' @importFrom sf st_drop_geometry
#' @importFrom dplyr select starts_with filter group_by summarise mutate inner_join all_of arrange desc
#' @importFrom tidyr pivot_longer
#' @importFrom scales number
#' @importFrom readr read_csv2
#' 
#' 
#' @noRd
get_data_budget_by_theme_selected_projects <- function(
    projects_data_sf, 
    language, 
    topic = NULL
) {
  
  data_graph_topic <-  projects_data_sf |> 
    st_drop_geometry() |>
    select(
      starts_with("topic_"),
      total_budget
    ) |> 
    pivot_longer(
      cols = starts_with("topic_"),
      names_to = "name",
      values_to = "present"
    ) |> 
    filter(
      present
    ) |> 
    group_by(name) |>  
    summarise(
      value = sum(total_budget, na.rm = TRUE)
    ) |> 
    mutate(
      value_tooltip = number(
        value,
        suffix = " CHF"
      )
    )
  
  # Filter only a specific project
  if (!is.null(topic)) {
    data_graph_topic <- data_graph_topic |> 
      filter(name %in% topic)
  }
  
  dic_variables <- suppressMessages(
    read_csv2(
      file = app_sys("data-dic/dic_variables.csv"),
      show_col_types = FALSE
    )
  )
  
  data_graph_topic_translated <- data_graph_topic |> 
    inner_join(
      dic_variables,
      by = c("name" = "name_variable")
    ) |> 
    select(
      name = all_of(language), 
      value, 
      value_tooltip
    ) |> 
    arrange(
      desc(value)
    )
  
  return(data_graph_topic_translated)
}
```
  
```{r example-get_data_budget_by_theme_selected_projects}
data("toy_projects_data_sf")

get_data_budget_by_theme_selected_projects(
  projects_data_sf = toy_projects_data_sf,
  language = "fr"
)

get_data_budget_by_theme_selected_projects(
  projects_data_sf = toy_projects_data_sf,
  language = "fr", 
  topic = "topic_diabetes"
)

get_data_budget_by_theme_selected_projects(
  projects_data_sf = toy_projects_data_sf,
  language = "fr", 
  topic = c(
    "topic_diabetes", 
    "topic_addictions"
  )
  
)
```
  
```{r tests-get_data_budget_by_theme_selected_projects}
test_that(
  "get_data_budget_by_theme_selected_projects() yield propre data.frame for FR data", {
  
  data("toy_projects_data_sf")
    
  data_graph_topic <- get_data_budget_by_theme_selected_projects(
    projects_data_sf = toy_projects_data_sf,
    language = "fr"
  )
  
  # Colnames and classes are the expected ones
  expect_equal(
    vapply(data_graph_topic, class, character(1)),
    c(
      name = "character",
      value = "numeric",
      value_tooltip = "character"
    )
  )
  
})

test_that(
  "get_data_budget_by_theme_selected_projects() yield propre data.frame for DE data", {
  
  data("toy_projects_data_sf")
    
  data_graph_topic <- get_data_budget_by_theme_selected_projects(
    projects_data_sf = toy_projects_data_sf,
    language = "de"
  )
  
  # Colnames and classes are the expected ones
  expect_equal(
    vapply(data_graph_topic, class, character(1)),
    c(
      name = "character",
      value = "numeric",
      value_tooltip = "character"
    )
  )
  
})
```
  
# Get budget data by year for selected projects

```{r function-get_data_budget_by_year_selected_projects}
#' Get budget data by year for selected projects
#' 
#' @param projects_data_sf Tibble. Data projects.
#' @param language Character. Language, 'fr' or 'de'.
#'
#' @return A tibble with three columns: `name`, `value` and `value_tooltip`
#' 
#' @importFrom sf st_drop_geometry
#' @importFrom dplyr select group_by summarise mutate rename
#' @importFrom scales number
#' 
#' @noRd
get_data_budget_by_year_selected_projects <- function(
    projects_data_sf, 
    language
) {
  
  if (language == "fr") {
    
    word_en <- "en"
    word_cum <- "cumul\u00e9 depuis"
    
  } else if (language == "de") {
    
    word_en <- "im Jahr"
    word_cum <- "kumuliert seit"
    
  }
  
  projects_data_sf |>
    st_drop_geometry() |> 
    mutate(
      # Extract year pattern
      year = gsub(
        pattern = "^\\w+ +(\\d{4})$",
        replacement = "\\1",
        funding_round
      )
    ) |> 
    select(
      year,
      total_budget
    ) |> 
    group_by(year) |> 
    summarise(
      sum_value = sum(total_budget, na.rm = TRUE),
    ) |> 
    mutate(
      value = cumsum(sum_value)
    ) |> 
    mutate(
      value_tooltip = paste(
        paste(
          number(
            sum_value,
            suffix = " CHF"
            ), 
          word_en, 
          year
        ),
        paste(
          number(
            value,
            suffix = " CHF"
          ), 
          word_cum, 
          min(year)
        ),
        sep = "<br>"
      )
    ) |> 
    rename(
      name = year
    )
  
}
```
  
```{r example-get_data_budget_by_year_selected_projects}
data("toy_projects_data_sf")

get_data_budget_by_year_selected_projects(
  projects_data_sf = toy_projects_data_sf, 
  language = "fr"
)
```
  
```{r tests-get_data_budget_by_year_selected_projects}
test_that(
  "get_data_budget_by_year_selected_projects() yield propre data.frame for FR data", {
  
  data("toy_projects_data_sf")
    
  data_graph_year <- get_data_budget_by_year_selected_projects(
    projects_data_sf = toy_projects_data_sf, 
    language = "fr"
  )
  
  # Colnames and classes are the expected ones
  expect_equal(
    vapply(data_graph_year, class, character(1)),
    c(
      name = "character",
      sum_value = "numeric",
      value = "numeric",
      value_tooltip = "character"
    )
  )
  
})

test_that(
  "get_data_budget_by_year_selected_projects() yield propre data.frame for DE data", {
  
  data("toy_projects_data_sf")
    
  data_graph_year <- get_data_budget_by_year_selected_projects(
    projects_data_sf = toy_projects_data_sf, 
    language = "de"
  )
  
  # Colnames and classes are the expected ones
  expect_equal(
    vapply(data_graph_year, class, character(1)),
    c(
      name = "character",
      sum_value = "numeric",
      value = "numeric",
      value_tooltip = "character"
    )
  )
  
})
```
  

```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(
  flat_file = "dev/flat_plot_budget_subfunctions.Rmd", 
  vignette_name = NA, 
  check = FALSE,
  overwrite = TRUE, 
  open_vignette = FALSE
)
```

