---
title: "Draw the distribution of contributions"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
library(purrr)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

*The aim of this article is to show you how to reproduce the interactive charts that represent the distribution of the budgets.*

# Plot the distribution of the budgets

To create the interactive plot, you can use the `plot_budget_highcharter()` function as follows *(here with a toy dataset)*:

```{r function-plot_budget_highcharter}
#' Plot the distribution of the budgets
#' 
#' @param id Character. Id of the container in the DOM.
#' @param data_repart Tibble. Data to be plotted.
#' @param plot_options List. List of options for the plot.
#' @param session Session object.
#' 
#' @importFrom purrr pmap set_names
#' @importFrom dplyr mutate
#' 
#' @return A Java Script plot
#' 
#' @export
plot_budget_highcharter <- function(
    id,
    data_repart,
    plot_options = list(
      axis_max = 100,
      axis_interval = 20,
      series_name = "",
      prefixer = "%"
    ),
    session
){
  
  # Transform the data in the right format
  data_to_compare <- pmap(
    list(
      data_repart$name, 
      data_repart$value, 
      data_repart$value_tooltip
    ), 
    ~ list(
      name = ..1, 
      value = ..2, 
      value_tooltip = ..3
    )
  ) |> 
    set_names(
      paste0(
        "place", 
        seq(from = 1, to = nrow(data_repart), by = 1)
      )
    )
  
  data <- list(
    id = id,
    plot_options = plot_options,
    data_to_compare = data_to_compare
  )
  
  # Transform the data in the right format
  session$sendCustomMessage(
    type = "createChart",
    message = list(
      data
    )
  )
  
}
```

```{r example-plot_budget_highcharter, eval=FALSE}
toy_data_repart <- tibble::tibble(
  name = c("Item 1", "Item 2"),
  value = c(75, 25), 
  value_tooltip = c("75 000 CHF", "25 000 CHF")
)

# plot_budget_highcharter(
#   id = "id-in-the-dom-maybe-with-ns",
#   data_repart = toy_data_repart,
#   session = session
# )
```

```{r tests-plot_budget_highcharter}
test_that("plot_budget_highcharter works", {
  expect_true(inherits(plot_budget_highcharter, "function")) 
})
```


```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(
  flat_file = "dev/flat_plot_budget.Rmd", 
  vignette_name = "Draw the distribution of contributions", 
  check = FALSE,
  overwrite = TRUE, 
  open_vignette = FALSE
  )
```

