# WARNING - Generated by {fusen} from dev/flat_prepare_data_subfunctions.Rmd: do not edit by hand

test_that("Test that the geocoding of the data is ok", {
  
  toy_data <-
    structure(
      list(
        city_code_main_resp_orga = c(
          "Zürich",
          "Sion",
          "Bern",
          "Lausanne",
          "St. Gallen",
          NA,
          "Le Cerneux-Veusil",
          "Genève",
          "Aarau",
          "Münsingen"
        )
      ),
      row.names = c(NA,
                    -10L),
      class = c("tbl_df", "tbl", "data.frame")
    )
  
  #' @description Testing that there is a message if there is an issue
  expect_message(
    res_geocode <- get_coord_main_resp_orga(
      data = toy_data
    ),
    regexp = "1 project.s is.are not associated to a city."
  )
  
  #' @description Testing that there is no error is an usual situation
  expect_error(
    res_geocode <- get_coord_main_resp_orga(
      data = toy_data
    ),
    regexp = NA
  )
  
})
