# WARNING - Generated by {fusen} from dev/flat_prepare_data_subfunctions.Rmd: do not edit by hand

test_that("Test that the preparation of a project card works", {
  
  data("toy_projects_data_sf")
  
  # Create a temp folder with data-projects-cards subfolder
  my_temp_dir <- tempfile("test-create-project-card")
  dir.create(my_temp_dir)
  dir.create(file.path(my_temp_dir, "data-projects-cards"))
  
  file.copy(
    from = app_sys(
      "data-projects-cards", 
      "template_projects_cards.html"
    ), 
    to = file.path(
      my_temp_dir, 
      "data-projects-cards", 
      "template_projects_cards.html"
    )
  )
  
  prepare_one_project_card(
    id_project = "1+1=3  PGV03.038",
    data_projects = toy_projects_data_sf,
    language = "de", 
    pkg_dir = my_temp_dir
  )
  
  expect_true(
    file.exists(
      file.path(
         my_temp_dir, 
        "data-projects-cards", 
        "project_card_113PGV03038_de.html"
      )
    )
  )
  
  unlink(my_temp_dir, recursive = TRUE)
  
})
