# WARNING - Generated by {fusen} from dev/flat_prepare_data_subfunctions.Rmd: do not edit by hand

test_that("Test that the computation of the prop of the budget is ok", {
  
  toy_data <-
    structure(
      list(
        budget_gfch = c(2e+05, 2e+06, 1500000, 182635),
        budget_orga = c(25000, 1714500, 160346, 45000),
        budget_third_party = c(361720,
                               380000, 1500000, 20000),
        total_budget = c(586720, 4094500,
                         3160346, 247635)
      ),
      row.names = c(NA, -4L),
      class = c("tbl_df",
                "tbl", "data.frame")
    )
  
  res_prop_budget <- toy_data |> 
    get_prop_budget() |> 
    dplyr::mutate(
      sum_prop_budget = 
        prop_budget_gfch + 
        prop_budget_third_party + 
        prop_budget_orga
    )
  
  #' @description Testing that the sum of all the proportion equals 1
  expect_true(
    object = all(res_prop_budget$sum_prop_budget == 1)
  )
  
})
