# WARNING - Generated by {fusen} from dev/flat_prepare_data_subfunctions.Rmd: do not edit by hand

test_that("Test that the addition of the variables names is ok", {
  
  raw_projects_data <- import_raw_data()
  
  # Add colnames
  raw_data_with_colnames <- add_col_raw_data(
    data = raw_projects_data
  )
  
  # Import the variables dictionary saved in the package
  dic_variables <- read_csv2(
    system.file("dic_variables.csv", package = "observatoire"),
    show_col_types = FALSE
  )
  
  #' @description Testing that the colnames are the expected ones
  expect_equal(
    object = sort(colnames(raw_data_with_colnames)), 
    expect = sort(dic_variables$name_variable)
  )
  
  colnames(raw_data_with_colnames) <- colnames(raw_projects_data)
  
  #' @description Testing that the data is not modified
  expect_equal(
    object = raw_data_with_colnames, 
    expect = raw_projects_data
  )
  
  colnames(raw_projects_data)[1] <- "mistake"
  #' @description Testing that there is an error if columns are not the expected ones
  expect_error(
    add_col_raw_data(
      data = raw_projects_data
    )
  )
  
})
