# WARNING - Generated by {fusen} from dev/flat_filter_project_data.Rmd: do not edit by hand

test_that("get_topics_to_display() works in FR", {
  projects_data_sf <- load_projects_data(
    language = "fr"
  )
  topics_to_display <- get_topics_to_display(
    projects_data_sf = projects_data_sf
  )
  
  expect_type(
    topics_to_display,
    "character"
  )
  
  # Other topics are featured at the very end of the vector
  id_other_topics <- grep("Andere|Autre", topics_to_display)
  expect_setequal(
    id_other_topics,
    seq(
      from = length(topics_to_display), 
      length.out = length(id_other_topics), 
      by = -1
    )
  )
})

test_that("get_topics_to_display() works in DE", {
  projects_data_sf <- load_projects_data(
    language = "de"
  )
  topics_to_display <- get_topics_to_display(
    projects_data_sf = projects_data_sf
  )
  
  expect_type(
    topics_to_display,
    "character"
  )
  
  # Other topics are featured at the very end of the vector
  id_other_topics <- grep("Andere|Autre", topics_to_display)
  expect_setequal(
    id_other_topics,
    seq(
      from = length(topics_to_display), 
      length.out = length(id_other_topics), 
      by = -1
    )
  )
})

