# WARNING - Generated by {fusen} from dev/flat_prepare_data_subfunctions.Rmd: do not edit by hand

test_that("Test that the translation of a column works", {
  
  # Load the toy datasets
  data("toy_data_pgv")
  data("toy_dic_variables")
  data("toy_dic_values")
  
  # Import the raw data and perform the first preparations
  raw_data <- toy_data_pgv |>
    add_col_raw_data(
      dic_variables = toy_dic_variables
    ) |>
    clean_raw_data()
  
  # Translate the column status
  col_status_fr <- translate_values_in_col(
    data = raw_data,
    col_to_translate = "status",
    dic_values = toy_dic_values,
    language = "fr"
  )$status |> unique()
  
  expect_equal(
    object = col_status_fr, 
    expected = c(
      "Termin\u00e9", 
      "En cours"
    )
  )
  
  col_status_de <- translate_values_in_col(
    data = raw_data,
    col_to_translate = "status",
    dic_values = toy_dic_values,
    language = "de"
  )$status |> unique()
  
  expect_equal(
    object = col_status_de, 
    expected = c(
      "Abschluss", 
      "Umsetzung"
    )
  )
  
  # Translate the column topic
  col_topic_fr <- translate_values_in_col(
    data = raw_data,
    col_to_translate = "topic",
    dic_values = toy_dic_values,
    language = "fr"
  )$topic |> unique()
  
  expect_equal(
    object = col_topic_fr, 
    expected = c(
      "D\u00e9pendances", 
      "Diab\u00e8tes",
      "Autres th\u00e8mes, Maladies mentales", 
      "Autres th\u00e8mes, Maladies respiratoires, Cancers, Maladies musculosquelettiques, D\u00e9pendances"
    )
  )
  
})
