# WARNING - Generated by {fusen} from dev/flat_plot_budget_subfunctions.Rmd: do not edit by hand

test_that(
  "get_data_budget_by_theme_selected_projects() yield propre data.frame for FR data", {
  
  language <- "fr"
  projects_data_sf <- load_projects_data(language) 
  data_graph_topic <- get_data_budget_by_theme_selected_projects(
    projects_data_sf = projects_data_sf,
    language = language
  )
  
  # Colnames and classes are the expected ones
  expect_equal(
    vapply(data_graph_topic, class, character(1)),
    c(
      name = "character",
      value = "numeric",
      value_tooltip = "character"
    )
  )
  
})

test_that(
  "get_data_budget_by_theme_selected_projects() yield propre data.frame for DE data", {
  
  language <- "de"
  projects_data_sf <- load_projects_data(language) 
  data_graph_topic <- get_data_budget_by_theme_selected_projects(
    projects_data_sf = projects_data_sf,
    language = language
  )
  
  # Colnames and classes are the expected ones
  expect_equal(
    vapply(data_graph_topic, class, character(1)),
    c(
      name = "character",
      value = "numeric",
      value_tooltip = "character"
    )
  )
  
})
