# WARNING - Generated by {fusen} from dev/flat_prepare_data_subfunctions.Rmd: do not edit by hand

test_that("Test that the addition of the variables names is ok", {
  
  # Load the raw data
  data("toy_data_pgv")
  
  # Load the variables dictionary
  data("toy_dic_variables")

  # Add colnames
  raw_data_with_colnames <- add_col_raw_data(
    data = toy_data_pgv,
    dic_variables = toy_dic_variables
  )
  
  #' @description Testing that the colnames are the expected ones
  expect_equal(
    object = sort(colnames(raw_data_with_colnames)), 
    expect = sort(toy_dic_variables$name_variable)
  )
  
  colnames(raw_data_with_colnames) <- colnames(toy_data_pgv)
  
  #' @description Testing that the data is not modified
  expect_equal(
    object = raw_data_with_colnames, 
    expect = toy_data_pgv
  )
  
  colnames(toy_data_pgv)[1] <- "mistake"
  #' @description Testing that there is an error if columns are not the expected ones
  expect_error(
    add_col_raw_data(
      data = toy_data_pgv
    )
  )
  
})
