# WARNING - Generated by {fusen} from dev/flat_prepare_data_subfunctions.Rmd: do not edit by hand

test_that("Test that the cleaning of the raw data is ok", {
 
  raw_data <- import_raw_data()
  
  clean_data <- raw_data |>
    add_col_raw_data() |>
    clean_raw_data()
  
  #' @description Testing that there is not more issue with French word in the first line
  expect_false(
    object = (clean_data[1, 1] == "Titre")
  )
  
  #' @description Testing that there is not more issue with the thousand sep
  expect_equal(
    object = clean_data |>
      dplyr::filter(
        dplyr::if_any(
          tidyselect::starts_with("budget"),
                    ~ grepl("^CHF|\\'", .x))) |>
      nrow(), 
    expected = 0
  )
  
  
  

  
  
})
