# WARNING - Generated by {fusen} from dev/flat_plot_budget.Rmd: do not edit by hand

test_that("plot_contrib_budget_highcharter works", {
  expect_true(inherits(plot_contrib_budget_highcharter, "function")) 
})
