# WARNING - Generated by {fusen} from dev/flat_plot_budget_subfunctions.Rmd: do not edit by hand

test_that(
  "get_data_budget_by_year_selected_projects() yield propre data.frame for FR data", {
  
  data_graph_year <- get_data_budget_by_year_selected_projects(
    projects_data_sf = load_projects_data("fr")
  )
  
  # Colnames and classes are the expected ones
  expect_equal(
    vapply(data_graph_year, class, character(1)),
    c(
      name = "character",
      value = "numeric",
      value_tooltip = "character"
    )
  )
  
})

test_that(
  "get_data_budget_by_year_selected_projects() yield propre data.frame for DE data", {
  
  data_graph_year <- get_data_budget_by_year_selected_projects(
    projects_data_sf = load_projects_data("de")
  )
  
  # Colnames and classes are the expected ones
  expect_equal(
    vapply(data_graph_year, class, character(1)),
    c(
      name = "character",
      value = "numeric",
      value_tooltip = "character"
    )
  )
  
})
