# WARNING - Generated by {fusen} from dev/flat_plot_budget_subfunctions.Rmd: do not edit by hand

test_that("get_data_repart_budget_one_project works", {
  expect_true(inherits(get_data_repart_budget_one_project, "function")) 
})
