# WARNING - Generated by {fusen} from dev/flat_filter_project_data.Rmd: do not edit by hand

test_that("get_input_data_to_display() works", {
  expect_error(
    get_input_data_to_display(
      language = "fr",
      pattern = "^topic_"
    ),
    NA
  )
})
