# WARNING - Generated by {fusen} from dev/flat_map.Rmd: do not edit by hand

test_that("read_cantons_sf works", {
  cantons_sf <- read_cantons_sf()
  
  expect_equal(
    colnames(cantons_sf),
    c(
      "GID_1",
      "GID_0",
      "COUNTRY",
      "NAME_1",
      "VARNAME_1",
      "NL_NAME_1",
      "TYPE_1",
      "ENGTYPE_1",
      "CC_1",
      "HASC_1",
      "ISO_1",
      "geometry"
    )
  )
  
  expect_equal(
    dim(cantons_sf),
    c(26L, 12L)
  )
  
  expect_s3_class(
    cantons_sf,
    c("sf", "data.frame")
  )
  
})

test_that("Switzerland centroid are coherent between computation and accessor function", {
  expect_equal(
    compute_switzerland_centroid(),
    get_switzerland_centroid()
  )
})

test_that("Switzerland bounding box are coherent between computation and accessor function", {
  expect_equal(
    compute_switzerland_bounding_box(),
    get_switzerland_bounding_box()
  )
})
