# WARNING - Generated by {fusen} from dev/flat_prepare_data_subfunctions.Rmd: do not edit by hand

test_that("Test that the computation of the nb of cantons is ok", {
  
  toy_data <-
    structure(
      list(
        geo_range = c(
          "Aargau,\r\nSt. Gallen",
          "Wallis",
          "Appenzell Ausserrhoden,\r\nAppenzell Innerrhoden,\r\nBasel-Landschaft,\r\nBasel-Stadt,\r\nBern,\r\nGenf,\r\nLuzern,\r\nNidwalden,\r\nObwalden,\r\nSt. Gallen,\r\nThurgau,\r\nWaadt,\r\nZ\u00fcrich",
          "Z\u00fcrich"
        )
      ),
      row.names = c(NA, -4L),
      class = c("tbl_df", "tbl",
                "data.frame")
    )
  
  res_nb_cantons_influenced <- toy_data |> 
    get_nb_cantons_influenced()
  
  #' @description Testing that the feature provide the expected output
  expect_equal(
    object = res_nb_cantons_influenced$nb_cantons_influenced,
    expected = c(2, 2, 13, 2)
  )
  
})
