# WARNING - Generated by {fusen} from dev/flat_prepare_data_subfunctions.Rmd: do not edit by hand

test_that("compute_project_completion_percentage works", {
  # We need a dummy binding to be able to mock a function from {base}
  Sys.Date <- NULL
  with_mocked_bindings(
    code = {
      completion_percentage <- compute_project_completion_percentage(
        date_project_start = as.Date("2023-01-01"),
        date_project_end = as.Date("2026-12-31")
      )
    },
    Sys.Date = function() as.Date("2024-03-04") 
  )  
  expect_equal(
    completion_percentage,
    29
  )
})
