# WARNING - Generated by {fusen} from dev/flat_filter_project_data.Rmd: do not edit by hand

test_that("get_prop_self_funded_range() yield well formed range in FR", {
  projects_data_sf <- load_projects_data("fr") 
  budget_range <- get_prop_self_funded_range(projects_data_sf)
  expect_length(
    budget_range,
    2
  )
  expect_type(
    budget_range,
    "double"
  )
})
test_that("get_prop_self_funded_range() yield well formed range in DE", {
  projects_data_sf <- load_projects_data("de") 
  budget_range <- get_prop_self_funded_range(projects_data_sf)
  expect_length(
    budget_range,
    2
  )
  expect_type(
    budget_range,
    "double"
  )
})
