# WARNING - Generated by {fusen} from dev/flat_prepare_data_subfunctions.Rmd: do not edit by hand

test_that("Test that the preparation of all cards works", {
  
  # Load the toy datasets
  data("toy_projects_data_sf")
  data("toy_dic_titles_pages")
  
  # Keep 2 projects
  toy_data <- toy_projects_data_sf[1:2,]
  
  # Create a temp folder with data-projects-cards subfolder
  my_temp_dir <- tempfile("test-create-project-card")
  dir.create(my_temp_dir)
  dir.create(file.path(my_temp_dir, "data-projects-cards"))
  
  file.copy(
    from = app_sys("data-projects-cards",
                   "template_projects_cards.html"),
    to = file.path(
      my_temp_dir,
      "data-projects-cards",
      "template_projects_cards.html"
    )
  )
  
  prepare_projects_cards(
    data_projects_fr = toy_data,
    data_projects_de = toy_data,
    dic_titles_pages = toy_dic_titles_pages,
    pkg_dir = my_temp_dir
  )
  
  expect_true(
    file.exists(
      file.path(
        my_temp_dir,
        "data-projects-cards",
        "project_card_113PGV03038_de.html"
      )
    )
  )
  
  expect_true(
    file.exists(
      file.path(
        my_temp_dir,
        "data-projects-cards",
        "project_card_113PGV03038_fr.html"
      )
    )
  )
  
  expect_true(
    file.exists(
      file.path(
        my_temp_dir,
        "data-projects-cards",
        "project_card_ActionDiabetePGV01057_de.html"
      )
    )
  )
  
  expect_true(
    file.exists(
      file.path(
        my_temp_dir,
        "data-projects-cards",
        "project_card_ActionDiabetePGV01057_fr.html"
      )
    )
  )
  
  unlink(my_temp_dir, recursive = TRUE)
  
})
