# WARNING - Generated by {fusen} from dev/flat_prepare_data_subfunctions.Rmd: do not edit by hand

test_that("Test that the import of the raw data is ok", {
  
  # Create a temp folder with data-raw subfolder and save a toy object inside
  my_temp_dir <- tempfile("test-import-data")
  dir.create(my_temp_dir)
  dir.create(file.path(my_temp_dir, "data-raw"))
  
  writexl::write_xlsx(
    x = iris[1:2, ], 
    path = file.path(my_temp_dir, "data-raw", "iris.xlsx")
  )
  
  write.csv(
    x = iris[1:2, ], 
    file = file.path(my_temp_dir, "data-raw", "iris.csv")
  )
  
  #' @description Testing that there is no error if the xlsx data exists
  expect_error(
    res_iris_import <- import_raw_data(
      name_raw_file = "iris.xlsx",
      pkg_dir = my_temp_dir
    ), regexp = NA
  )
  
  #' @description Testing that the object is the expected one
  expect_equal(
    object = res_iris_import |> 
      dplyr::mutate(
        dplyr::across(
          everything(),
          as.character
        )),
    expected = tibble::as_tibble(iris[1:2, ]) |> 
      dplyr::mutate(
        dplyr::across(
          everything(),
          as.character
        ))
  )
  
  #' @description Testing that there is an error if the data does not exist
  expect_error(
    import_raw_data(
      name_raw_file = "notexists.xlsx",
      pkg_dir = my_temp_dir
    )
  )
  
  #' @description Testing that there is an error if the data is not a xlsx file
  expect_error(
    import_raw_data(
      name_raw_file = "iris.csv",
      pkg_dir = my_temp_dir
    )
  )
  
  unlink(
    my_temp_dir, 
    recursive = TRUE
  )
  
})
