# WARNING - Generated by {fusen} from dev/flat_prepare_data_subfunctions.Rmd: do not edit by hand

test_that("Test that the detection of the canton is ok", {
  
  toy_data <-
    structure(
      list(
        short_title = c(
          "Starke Familie",
          "StoppSturz",
          "Sturzprävention in der Spitex",
          "WilaDina",
          "Win Back Control PGV01.002",
          "WOPM PGV02.015",
          "Zigzag Plus PGV02.064",
          "FM_ProPCC+"
        ),
        longitude = c(
          8.0444448,
          9.3762397,
          8.7954859,
          7.5631943,
          8.5410422,
          7.4521749,
          6.6327025,
          NA
        ),
        latitude = c(
          47.3927146,
          47.425618,
          46.1695739,
          46.8739775,
          47.3744489,
          46.9484742,
          46.5218269,
          NA
        )
      ),
      row.names = c(NA, -8L),
      class = c("tbl_df", "tbl", "data.frame")
    )
  
  expect_message(
    get_canton_main_resp_orga(
      data = toy_data
    ), 
    regexp = "1 project.s is.are not associated to a GPS point"
  )
  
  expect_error(
    res_toy_data <- get_canton_main_resp_orga(
      data = toy_data
    ), 
    regexp = NA
  )
  
  expect_equal(
    object = res_toy_data$name_canton,
    expected = c(
      "Aargau",
      "SanktGallen",
      "Ticino",
      "Bern",
      "Zürich",
      "Bern",
      "Vaud",
      NA
    )
  )
  
})
