# WARNING - Generated by {fusen} from dev/flat_fct_utils.Rmd: do not edit by hand

test_that("get_back_arrow_html works", {
  expect_s3_class(
    get_back_arrow_html(),
    c("html", "character")
  )
})
