# WARNING - Generated by {fusen} from dev/flat_filter_project_data.Rmd: do not edit by hand

test_that("get_cantons_main_org() yields well-formed vector in FR", {
  projects_data_sf <- load_projects_data("fr") 
  cantons_main_org <- get_cantons_main_org(projects_data_sf)
  expect_type(
    cantons_main_org,
    "character"
  )
  expect_true(
    all(
      !grepl(
        pattern = "^CH\\.",
        names(cantons_main_org)
      )
    )
  )
})

test_that("get_cantons_main_org() yields well-formed vector in DE", {
  projects_data_sf <- load_projects_data("de") 
  cantons_main_org <- get_cantons_main_org(projects_data_sf)
  expect_type(
    cantons_main_org,
    "character"
  )
  expect_true(
    all(
      !grepl(
        pattern = "^CH\\.",
        names(cantons_main_org)
      )
    )
  )
})
