# WARNING - Generated by {fusen} from dev/flat_fct_utils.Rmd: do not edit by hand

test_that("read_cantons_sf works", {
  cantons_sf <- read_cantons_sf()
  
  expect_equal(
    colnames(cantons_sf),
    c(
      "GID_1",
      "GID_0",
      "COUNTRY",
      "NAME_1",
      "VARNAME_1",
      "NL_NAME_1",
      "TYPE_1",
      "ENGTYPE_1",
      "CC_1",
      "HASC_1",
      "ISO_1",
      "geometry"
    )
  )
  
  expect_equal(
    dim(cantons_sf),
    c(26L, 12L)
  )
  
  expect_s3_class(
    cantons_sf,
    c("sf", "data.frame")
  )
  
})

test_that("psch color function return proper color",{
  expect_equal(
    psch_blue(),
    "#578397"
  )
  expect_equal(
    psch_orange(),
    "#f59300"
  )
})
