# WARNING - Generated by {fusen} from dev/flat_prepare_data_subfunctions.Rmd: do not edit by hand

test_that("consolidate_topic_data() preserves information", {
  
  # Same column names before and after consolidation
  toy_data <- toy_data_pgv |> 
    add_col_raw_data(
      dic_variables = toy_dic_variables
    ) |> 
    clean_raw_data() 
  
  toy_data_consolidated <- toy_data |> consolidate_topic_data()
  
  expect_setequal(
    colnames(toy_data),
    colnames(toy_data_consolidated)
  )
  
  # Consolidation worked i.e. the same information is contained in the 
  # topic vs all topic_ binary columns
  topics_in_topic_column_consolidated <- toy_data_consolidated |>
    dplyr::select(
      short_title,
      topic
    ) |> 
    tidyr::separate_rows(
      topic,
      sep = ",*\r\n|, "
    ) |> 
    dplyr::arrange(
      short_title,
      topic
    )
  
  dic_variables_topic_de <- suppressMessages(
    read_csv2(
      system.file(
        "data-dic", 
        "dic_variables.csv", 
        package = "observatoire"
      ),
      show_col_types = FALSE
    ) 
  ) |> 
    dplyr::select(de, name_variable) |> 
    dplyr::filter(
      grepl(
        "^topic_",
        name_variable
      )
    )
  
  topics_in_topic_binary_columns_consolidated <- toy_data_consolidated |>
    dplyr::select(
      short_title,
      dplyr::starts_with("topic_")
    ) |> 
    tidyr::pivot_longer(
      data = _,
      cols = starts_with("topic_")
    ) |>
    dplyr::right_join(
      dic_variables_topic_de,
      by = c("name" = "name_variable")
    ) |> 
    dplyr::filter(
      value
    ) |> 
    dplyr::select(
      short_title,
      topic = de
    ) |> 
    dplyr::arrange(
      short_title,
      topic
    )
  
  topics_in_topic_column_consolidated_wo_na <- 
    topics_in_topic_column_consolidated |> 
    # Remove edge case project without topic 
    filter(
      !is.na(topic)
    )
  
  expect_equal(
    topics_in_topic_column_consolidated_wo_na,
    topics_in_topic_binary_columns_consolidated
  )
  
  # Topic character column is the same before and after consolidation
  topics_in_topic_column <- toy_data |> 
    dplyr::select(
      short_title,
      topic
    ) |> 
    tidyr::separate_rows(
      topic,
      sep = ",*\r\n|, "
    ) |> 
    dplyr::arrange(
      short_title,
      topic
    )
  expect_equal(
    topics_in_topic_column,
    topics_in_topic_column_consolidated
  )
})
