# WARNING - Generated by {fusen} from dev/flat_prepare_data_subfunctions.Rmd: do not edit by hand

#' Add the proper colums names to the projects data
#' 
#' @param data Tibble. Raw data about projects.
#' 
#' @importFrom readr read_csv2
#' 
#' @return The raw data about the projects with the good columns names.
#'
#' @noRd
#' @examples
#' # Import the raw data
#' raw_projetcs_data <- import_raw_data()
#'
#' # Add the good columns names
#' raw_projetcs_data |> 
#'   add_col_raw_data()
add_col_raw_data <- function(
    data
    ){
  
  # Import the variables dictionary saved in the package
  dic_variables <- read_csv2(
    system.file("dic_variables.csv", package = "observatoire"),
    show_col_types = FALSE
  )
  
  # Check if all columns are present
  if (isFALSE(all(sort(colnames(data)) == sort(dic_variables$de)))) {
    stop("The columns in the raw projects data file are not the expected ones. Please, make sure that the columns are those described in the file dic_variables.csv.")
  }
  
  # Replace german column names with the names of the variables
  colnames(data) <- dic_variables$name_variable[
    match(
      dic_variables$de, 
      names(data)
      )
    ]

  return(data)
  
}
