# WARNING - Generated by {fusen} from dev/flat_prepare_data_subfunctions.Rmd: do not edit by hand

#' Clean the raw projects data
#' 
#' @param data Tibble. Raw data about projects, with the good columns names.
#' 
#' @importFrom dplyr mutate across
#' @importFrom tidyselect contains
#' 
#' @return A tibble with clean data.
#' 
#' @noRd
#' @examples
#' # Load the toy datasets
#' data("toy_data_pgv")
#' data("toy_dic_variables")
#'
#' toy_data <- toy_data_pgv |> 
#'   add_col_raw_data(
#'     dic_variables = toy_dic_variables
#'   )
#'
#' # Clean the data
#' toy_data |> 
#'   clean_raw_data()
clean_raw_data <- function(
    data
){
  
  # Remove the first row containing some French column names
  if (data[1, 1] == "Titre") {
    data <- data[-1, ] 
  }
  
  # Convert to digital format
  ## Standardize thousand separators in budget columns
  data_standardized_thousand_sep <- data |> 
    mutate(
      across(
        contains("budget"),
        ~ gsub("^CHF\\s+|\\'", "", .x)
      )
    )
  
  ## Convert to digital format
  clean_data <- data_standardized_thousand_sep |>
    mutate(
      across(
        contains("budget"),
        as.numeric
      )
    )
  
  return(clean_data)
  
}
