# WARNING - Generated by {fusen} from dev/flat_prepare_data_subfunctions.Rmd: do not edit by hand

#' Clean the raw projects data
#' 
#' @param data Tibble. Raw data about projects, with the good columns names.
#' 
#' @importFrom dplyr mutate across
#' @importFrom tidyselect starts_with
#' 
#' @return A tibble with clean data.
#' 
#' @noRd
#' @examples
#' # Import the raw data and add the good columns names
#' raw_data <- import_raw_data() |> 
#'   add_col_raw_data()
#'
#' # Clean the data
#' raw_data |> 
#'   clean_raw_data()
clean_raw_data <- function(
    data
    ){
    
  # Remove the first row containing some French column names
  if (data[1, 1] == "Titre") {
    data <- data[-1, ] 
  }
  
  # Convert to digital format
  ## Standardize thousand separators in budget columns
  data_standardized_thousand_sep <- data |> 
  mutate(
    across(
      starts_with("budget"),
      ~ gsub("^CHF\\s+|\\'", "", .x)
    )
  ) 
  
  ## Convert to digital format
  clean_data <- data_standardized_thousand_sep |>
    mutate(
      across(
        starts_with("budget"),
        as.numeric
      )
    )
  
  return(clean_data)
  
}
