# WARNING - Generated by {fusen} from dev/flat_fct_utils.Rmd: do not edit by hand

#' Create the skeleton of a dictionnary dataset
#' 
#' @importFrom readr wite_csv2
#' 
#' @return Nothing. Used for side effect to create the skeleton of a dictionary in a csv format.
#' 
#' @noRd
#' @examples
#' data("toy_data_pgv")
#' data("toy_dic_variables") 
#'
#' # Create a temp folder with data-projects-cards subfolder
#' my_temp_dir <- tempfile("test-create-skeleton-dic")
#' dir.create(my_temp_dir)
#'
#' data = toy_data_pgv |> 
#'   add_col_raw_data(
#'     dic_variables = toy_dic_variables
#'   ) 
#'
#' create_skeleton_dic(
#'   data = data, 
#'   cols = c("status", "topic", "risk_factors"),
#'   path_file = file.path(
#'     my_temp_dir, 
#'     "dic_values.csv"
#'   )
#' )
#'
#' readr::read_csv2(
#'   file.path(
#'     my_temp_dir, 
#'     "dic_values.csv"
#'   )
#' )
#'
#' unlink(my_temp_dir, recursive = TRUE)
create_skeleton_dic <- function(
    data,
    cols, 
    sep = ",*\r\n|, |;",
    path_file
    ){
  
  data_dic <-  tibble(
    value = paste(
      unlist(data[, cols]), 
      collapse = ", "
      ) |> 
      gsub(
        pattern = sep, 
        replacement = ", "
      ) |> 
      strsplit(split = ", ") |> 
      unlist() |> 
      unique(), 
  de = value, 
  fr = "todo"
  )
  
  write_csv2(
    data_dic, 
    path_file
  )

}
