# WARNING - Generated by {fusen} from dev/flat_map.Rmd: do not edit by hand

#' Draw main interactive map
#'
#' @param projects_data_sf A sf data.frame containing coordinates of project 
#' main organisation and project `short_title`.
#' 
#' @return A leaflet object.
#' 
#' @importFrom stats setNames
#' @importFrom sf st_as_sf st_read st_bbox st_union st_centroid st_geometry
#' @importFrom leaflet leaflet setView addTiles addCircleMarkers addProviderTiles
#' @importFrom leaflet leafletOptions setMaxBounds addPolygons
#' 
#' @noRd
#' @examples
#' draw_leaflet_map(
#'   projects_data_sf = dummy_project_data_sf()
#' )
draw_leaflet_map <- function(
    projects_data_sf
) {
  
  cantons_sf <- read_cantons_sf()
  
  switzerland_centroid <- get_switzerland_centroid()
  switzerland_bounding_box <- get_switzerland_bounding_box()
  
  zoom_level <- 8
  leaflet(
    data = projects_data_sf,
    options = leafletOptions(minZoom = zoom_level)    
  ) |>
    addTiles() |>
    addPolygons( 
      data = cantons_sf,
      weight = 1,
      color = "#578397",
      fillColor = "#578397",
      fillOpacity = 0.3
    ) |> 
    addCircleMarkers(
      color = "#f59300",
      stroke = FALSE,
      fillOpacity = 0.8,
      label = ~ as.character(short_title)
    ) |>
    addProviderTiles(
      provider = "CartoDB.Positron"
      ) |>
    setView(
      lng = switzerland_centroid[["lng"]],
      lat = switzerland_centroid[["lat"]],
      zoom = zoom_level
    ) |> 
    setMaxBounds(
      lng1 = switzerland_bounding_box[["xmin"]],
      lat1 = switzerland_bounding_box[["ymin"]],
      lng2 = switzerland_bounding_box[["xmax"]],
      lat2 = switzerland_bounding_box[["ymax"]]
    )
}
