# WARNING - Generated by {fusen} from dev/flat_map.Rmd: do not edit by hand

#' Draw map of selected projects
#' 
#' @param projects_data_sf A sf data.frame containing coordinates of project 
#' main organisation and project `short_title`.
#' 
#' @param zoom_level An integer. The zoom level for the map. Defines
#' default zoom level.
#' 
#' @return A leaflet object.
#' 
#' @importFrom leaflet addCircleMarkers  addPolygons
#' 
#' @export
#' @examples
#' data("toy_projects_data_sf")
#'
#' draw_map_selected_projects(
#'   projects_data_sf = toy_projects_data_sf
#' )
draw_map_selected_projects <- function(
    projects_data_sf,
    zoom_level = 8
){
  
  my_map <- draw_map_base(zoom_level) |> 
    addPolygons(
      data = read_cantons_sf(),
      weight = 1,
      color = psch_blue(),
      fillColor = psch_blue(),
      fillOpacity = 0.2
    ) |>
    addCircleMarkers(
      data = projects_data_sf,
      color = psch_orange(),
      stroke = FALSE,
      fillOpacity = 0.8,
      layerId = ~ short_title,
      label = ~ as.character(short_title)
    )
  
  class(my_map) <- c(
    class(my_map),
    "all-projects"
  )
  
  return(my_map)
  
}
