# WARNING - Generated by {fusen} from dev/flat_map.Rmd: do not edit by hand

#' Draw main interactive map
#'
#' @return A leaflet object.
#' 
#' @importFrom stats setNames
#' @importFrom sf st_as_sf st_read st_bbox st_union st_centroid st_geometry
#' @importFrom leaflet leaflet setView addTiles  addMarkers addProviderTiles
#' @importFrom leaflet leafletOptions setMaxBounds addPolygons
#' 
#' @noRd
#' @examples
#' draw_leaflet_map()
draw_leaflet_map <- function() {

  # Dummy data for prototyping only
  dummy_sf <- data.frame(
    name = "PSCH",
    addr = "52 Avenue de la Gare, 1003 Lausanne, Switzerland",
    lat = 46.51756965,
    long = 6.63061493418584
  ) |>
    sf::st_as_sf(
      coords = c("long", "lat"),
      crs = 4326
    )
  
  cantons_sf <- st_read(
    dsn = system.file(
      "gadm41_CHE_1.json", 
      package = "observatoire"
    ),
    quiet = TRUE
  )
  
  cantons_bbox <- st_bbox(cantons_sf)
  switzerland_centroid <- cantons_sf |> 
    st_union() |> 
    st_centroid() |> 
    st_geometry() |> 
    unlist() |> 
    setNames(
      c("lng", "lat")
    )
  
  zoom_level <- 8
  leaflet(
    data = dummy_sf,
    options = leafletOptions(minZoom = zoom_level)    
  ) |>
    addTiles() |>
    addMarkers() |>
    addPolygons( 
      data = cantons_sf,
      weight = 1,
      color = "#578397",
      fillColor = "#578397",
      fillOpacity = 0.3
    ) |> 
    addProviderTiles(
      provider = "CartoDB.Positron"
      ) |>
    setView(
      lng = switzerland_centroid[["lng"]],
      lat = switzerland_centroid[["lat"]],
      zoom = zoom_level
    ) |> 
    setMaxBounds(
      lng1 = cantons_bbox[["xmin"]],
      lat1 = cantons_bbox[["ymin"]],
      lng2 = cantons_bbox[["xmax"]],
      lat2 = cantons_bbox[["ymax"]]
    )
}
