# WARNING - Generated by {fusen} from dev/flat_map.Rmd: do not edit by hand

#' Draw the map focused on one project
#' 
#' @param projects_data_sf A sf data.frame containing coordinates of project 
#' main organisation and project `short_title`.
#' @param id_project Character. Id of the project.
#' @param cantons_sf Sf data. Cantons geometry. Mainly used for examples and unit testing purpose.
#' @param zoom_level An integer. The zoom level for the map. Defines
#' default zoom level.
#' 
#' @importFrom leaflet addCircleMarkers addPolygons addPolylines labelOptions
#' @importFrom dplyr filter select mutate rename
#' @importFrom tibble as_tibble
#' @importFrom tidyr separate_rows
#' @importFrom sf st_drop_geometry st_centroid st_union st_cast
#'  
#' @return A leaflet object.
#' 
#' @export
#' @examples
#' data("toy_projects_data_sf")
#' data("toy_cantons_sf")
#'
#' draw_map_focus_one_project(
#'   projects_data_sf = toy_projects_data_sf,
#'   id_project = "1+1=3  PGV03.038", 
#'   cantons_sf = toy_cantons_sf
#' )
#'
#' draw_map_focus_one_project(
#'   projects_data_sf = toy_projects_data_sf,
#'   id_project = "FM_ProPCC+", 
#'   cantons_sf = toy_cantons_sf
#' )
draw_map_focus_one_project <- function(
    projects_data_sf,
    id_project,
    cantons_sf = NULL,
    zoom_level = 8
){

  if (is.null(cantons_sf)) {
    cantons_sf <- read_cantons_sf()
  }
  
  # Create a coord_sf_project object
  projects_data_sf_filtered <- projects_data_sf |> 
    filter(short_title == id_project) 
  
  coord_sf_project <- projects_data_sf_filtered |> 
    select(short_title, geometry)
  
  # Extract target cantons from project_data_sf
  project_data_cantons_sf <- projects_data_sf_filtered |> 
    st_drop_geometry() |> 
    select(short_title, geo_range_id) |> 
    separate_rows(
      geo_range_id, 
      sep = ", "
    )
  
  # Create a cantons_sf_project object with column target_cantons (TRUE/FALSE)
  cantons_sf_project <- left_join(
    x = cantons_sf |> 
      select(HASC_1, NAME_1, geometry),
    y = project_data_cantons_sf |> 
      rename(HASC_1 = geo_range_id), 
    by = "HASC_1"
  ) |> 
    mutate(
      target_cantons = ifelse(
        is.na(short_title),
        FALSE, 
        TRUE
      )
    ) |> 
    select(- short_title)
  
  # Draw the map
  # Display target cantons in psch orange / others psch blue
  # Display selected project in psch orange
  # Nice to have
  # Display lines radiating from project to centroid of target cantons
  map_with_not_influenced_cantons <- draw_map_base(zoom_level) |> 
    addPolygons(
      data = cantons_sf_project |> 
        filter(
          target_cantons == FALSE
        ),
      weight = 1,
      color = psch_blue(),
      fillColor = psch_blue(),
      fillOpacity = 0.2
    ) 
  
  if (nrow(cantons_sf_project |> 
        filter(target_cantons == TRUE)) > 0) {
    
    # Print the cantons in orange
    map_with_influenced_cantons <- map_with_not_influenced_cantons |> 
      addPolygons(
      data = cantons_sf_project |> 
        filter(
          target_cantons == TRUE
        ),
      weight = 1,
      color = psch_orange(),
      fillColor = psch_orange(),
      fillOpacity = 0.5,
      label = ~ as.character(HASC_1), 
      labelOptions = labelOptions(
        style = list("font-size" = "12px")  # Adjust the font size here
        )
      ) 
    
    # Add the lines
    cantons_centroid <- cantons_sf_project |>
      filter(
        target_cantons == TRUE
      ) |>
      st_centroid() |> 
      mutate(
        project = coord_sf_project$geometry
      )
    
    cantons_centroid_linestring <- st_union(
      cantons_centroid$geometry, 
      cantons_centroid$project
    ) |> 
    st_cast("LINESTRING")
    
    map_with_influenced_cantons <- map_with_influenced_cantons |> 
      addPolylines(
       data = cantons_centroid_linestring, 
       color = psch_orange(), 
       weight = 2
      )
      
  } else {
    
    map_with_influenced_cantons <- map_with_not_influenced_cantons
    
  }
    
  my_map <- map_with_influenced_cantons |>
    addCircleMarkers(
      data = coord_sf_project,
      color = psch_orange(),
      stroke = FALSE,
      fillOpacity = 0.8,
      label = ~ as.character(short_title)
    )
  
  class(my_map) <- c("one-project", class(my_map))
  
  return(my_map)
  
}
