# WARNING - Generated by {fusen} from dev/flat_fct_utils.Rmd: do not edit by hand

#' Read cantons polygons data
#' @importFrom sf st_read
#'
#' @noRd
read_cantons_sf <- function() {
  st_read(
    dsn = system.file(
      "data-geo",
      "gadm41_CHE_1.json", 
      package = "observatoire"
    ),
    quiet = TRUE
  )
}


#'
#' @noRd
psch_blue <- function() {
  # Meerblau
  "#578397"
} 

#'
#' @noRd
psch_orange <- function() {
  # Corporate: Orange
  "#f59300"
}
