# WARNING - Generated by {fusen} from dev/flat_filter_project_data.Rmd: do not edit by hand

#' Filter projects data
#' 
#' Main function that powers the filtering of  mod_projects_selection_*()
#' 
#' @param projects_data_sf A sf data.frame. 
#' @param vec_topics A character vector of topics 
#' @param range_budget A numeric vector of size two defining the lower and 
#' upper bound of budget.
#' @param range_self_funded_budget A numeric vector of size two defining the lower and
#'  upper bound of self-funded budget.
#' @param canton_main_resp_orga A character vector containing the names of the 
#' cantons of interest.
#'
#' @return A sf data.frame
#' 
#' @noRd
filter_projects_data <- function(
    projects_data_sf,
    vec_topics,
    range_budget,
    range_self_funded_budget,
    canton_main_resp_orga
){
  #   projects_data_sf |> 
  #     separate_rows(
  #       geo_range_id, 
  #       sep = ", "
  #     ) |> 
  #   filter(
  #     topic %in% vec_topics,
  #     total_budget |> between(
  #       min(range_budget), 
  #       max(range_budget)
  #     ),
  #     budget_orga |> 
  #       between(
  #         min(range_self_funded_budget), 
  #         max(range_self_funded_budget)
  #       ),
  #    geo_range_id %in% canton_main_resp_orga
  #   )
  return(projects_data_sf)
}
