# WARNING - Generated by {fusen} from dev/flat_filter_project_data.Rmd: do not edit by hand

#' @noRd
#' @examples
#' load_projects_data("fr") |> 
#'   get_prop_self_funded_range()
get_prop_self_funded_range <- function(
    projects_data_sf  
){
  range(
    projects_data_sf[["prop_budget_orga"]],
    na.rm = TRUE
  ) |> 
    round(
      digits = 2
    )
}
