# WARNING - Generated by {fusen} from dev/flat_plot_budget_subfunctions.Rmd: do not edit by hand

#' Get budget data by year for selected projects
#' 
#' @param projects_data_sf Tibble. Data projects.
#' @param language A character string. Language, 'fr' or 'de'.
#'
#' @return A tibble with three columns: `name`, `value` and `value_tooltip`
#' 
#' @importFrom sf st_drop_geometry
#' @importFrom dplyr select group_by summarise mutate rename
#' @importFrom scales number
#' 
#' @noRd
#' @examples
#' get_data_budget_by_year_selected_projects(
#'   projects_data_sf = load_projects_data("fr") 
#' )
get_data_budget_by_year_selected_projects <- function(
    projects_data_sf
) {
  
  projects_data_sf |>
    st_drop_geometry() |> 
    mutate(
      # Extract year pattern
      year = gsub(
        pattern = "^\\w+ +(\\d{4})$",
        replacement = "\\1",
        funding_round
      )
    ) |> 
    select(
      year,
      total_budget
    ) |> 
    group_by(year) |> 
    summarise(
      value = sum(total_budget, na.rm = TRUE)
    ) |> 
    mutate(
      value_tooltip = number(
        value,
        suffix = " CHF"
      )
    ) |> 
    rename(
      name = year
    )
  
}
