# WARNING - Generated by {fusen} from dev/flat_prepare_data_subfunctions.Rmd: do not edit by hand

#' Get the canton of the principale organization
#' 
#' @param data Tibble. Raw data about projects, with the good columns names.
#' @param cantons_sf Sf data. Cantons geometry. Mainly used for examples and unit testing purpose.
#' 
#' @importFrom dplyr filter mutate select left_join rename
#' @importFrom glue glue
#' @importFrom sf st_read st_intersects st_as_sf st_join
#' @importFrom purrr map_df 
#' @importFrom tibble as_tibble tibble
#' 
#' 
#' @return A tibble with the name of the canton
#' 
#' @noRd
#' @examples
#' # Load the toy datasets
#' data("toy_data_pgv")
#' data("toy_dic_variables")
#' data("toy_cantons_sf")
#'
#' toy_data <- toy_data_pgv |> 
#'   add_col_raw_data(
#'     dic_variables = toy_dic_variables
#'   ) |> 
#'   clean_raw_data() |> 
#'   get_coord_main_resp_orga(
#'     cantons_sf = toy_cantons_sf
#'   )
#'
#' # Geocode the principale organisation of the project
#' toy_data |> 
#'   get_canton_main_resp_orga(
#'     cantons_sf = toy_cantons_sf
#'   )
get_canton_main_resp_orga <- function(
    data, 
    cantons_sf = NULL
){
  
  # Check if some GPS points are missing
  nb_missing_gps_points <- data |> 
    filter(is.na(longitude) | is.na(latitude)) |> 
    nrow()
  
  if (nb_missing_gps_points > 0) {
    message(
      glue(
        "{nb_missing_gps_points} project.s is.are not associated to a GPS point.",
        "Please correct the problem before restarting the data preparation workflow,",
        "or this.these project.s will not be displayed on the observatory map.",
        .sep = "\n"
      )
    )
  }
  
  # Detect the id of the cantons
  if (is.null(cantons_sf)) {
    cantons_sf <- read_cantons_sf()
  }
  
  data_with_coord <- data |>
    select(short_title, geometry)
  
  data_with_id_canton <- st_join(
    x = data_with_coord, 
    y = select(cantons_sf, HASC_1)
  ) |> 
    rename(
      id_canton = HASC_1
    )
  
  # Add the canton to the raw data
  data_with_canton <- st_join(
    x = data, 
    y = data_with_id_canton,
    suffix = c("", "extra")
  ) |> 
    select(-short_titleextra)
  
  # Check if all cantons have been found
  nb_canton_not_found <- data_with_canton |> 
    filter(!is.na(longitude) & !is.na(latitude)) |> 
    filter(is.na(id_canton)) |> 
    nrow()
  
  if (nb_canton_not_found > 0) {
    stop(
      glue(
        "{nb_canton_not_found} project.s is.are not associated to a canton.",
        "Please correct the problem before restarting the data preparation workflow,",
        "or this.these project.s will not be displayed on the observatory map.",
        .sep = "\n"
      )
    )
  }
  
  return(data_with_canton)
  
}
