# WARNING - Generated by {fusen} from dev/flat_prepare_data_subfunctions.Rmd: do not edit by hand

#' Get the proportion of the budget for GFCH, principale organization and third party
#' 
#' @param data Tibble. Raw data about projects, with the good columns names.
#' 
#' @importFrom dplyr mutate across
#' @importFrom tidyselect starts_with
#' 
#' @return A tibble with 3 columns about the proportion of the budget paid by each actor
#' 
#' @noRd
#' @examples
#' # Import the raw data and perform the first preparations
#' raw_data <- import_raw_data() |> 
#'   add_col_raw_data() |> 
#'   clean_raw_data()
#'
#' # Get the proportion of the budget for GFCH, principale organization and third party
#' raw_data |> 
#'   get_prop_budget()
get_prop_budget <- function(
    data
    ){
  
  data |> 
    mutate(
      across(
        starts_with("budget_"), 
        ~ .x / total_budget, 
        .names = "prop_{.col}"
      )
    )
  
}
