# WARNING - Generated by {fusen} from dev/flat_prepare_data_subfunctions.Rmd: do not edit by hand

#' Get the coordinates of the principale organization
#' 
#' @param data Tibble. Raw data about projects, with the good columns names.
#'
#' @importFrom tidygeocoder geocode
#' @importFrom dplyr mutate select filter
#' @importFrom glue glue
#' @importFrom sf st_read st_contains st_point st_union st_as_sf
#' @importFrom purrr map_lgl
#' 
#' @return A tibble with a column with the coordinates of the principale organization.
#' 
#' @noRd
#' @examples
#' # Import the raw data and add the good columns names
#' raw_data <- import_raw_data() |> 
#'   add_col_raw_data() |> 
#'   clean_raw_data()
#'
#' # Geocode the principale organisation of the project
#' raw_data |> 
#'   get_coord_main_resp_orga()
get_coord_main_resp_orga <- function(
    data
){
  
  # Check if some cities are missing
  nb_missing_cities <- data |> 
    filter(is.na(city_code_main_resp_orga)) |> 
    nrow()
  
  if (nb_missing_cities > 0) {
    message(
      glue(
        "{nb_missing_cities} project.s is.are not associated to a city.",
        "Please correct the problem before restarting the data preparation workflow,",
        "or this.these project.s will not be displayed on the observatory map.",
        .sep = "\n"
      )
    )
  }
  
  data_with_coord <- data |> 
    mutate(
      country = "Switzerland"
    ) |> 
    geocode(
      city = city_code_main_resp_orga, 
      country = country,
      method = "osm", 
      lat = latitude , 
      long = longitude
    ) |> 
    select(- country)
  
  # Check if the points are in Switzerland
  cantons_sf <- st_read(
    dsn = system.file(
      "gadm41_CHE_1.json", 
      package = "observatoire"
    )
  )
  
  switzerland_sf <- st_union(
    x = cantons_sf
  )
  
  check_is_in_switzerland <- data_with_coord |> 
    filter(!is.na(longitude) & !is.na(latitude)) |> 
    st_as_sf(
      coords = c("longitude", "latitude"),
      crs = 4326
    ) |> 
    st_contains(
      x = switzerland_sf,
      y = _,
      sparse = FALSE
    ) |> 
    as.logical()
  
  
  if (any(isFALSE(check_is_in_switzerland))) {
    stop(
      paste(
        "There is an issue in the geocoding of the principale organisation.",
        "Some points that have been found are not in Switzerland.",
        sep = "\n"
      )
    )
  }
  
  return(data_with_coord)
  
}
