# WARNING - Generated by {fusen} from dev/flat_filter_project_data.Rmd: do not edit by hand

#' Get unique topics to display 
#'
#' and put "other" topics at the end.
#' 
#' @param projects_data_sf A sf data.frame holding the column `topic`.
#'
#' @return A character vector ending with "Other" (andere/autre) topics
#' 
#' @noRd
#' @examples
#' projects_data_sf <- load_projects_data(
#'   language = "fr"
#' )
#' get_topics_to_display(
#'   projects_data_sf = projects_data_sf
#' )
get_topics_to_display <- function(projects_data_sf) {
  
  topics <- projects_data_sf |>
    getElement("topic") |>
    strsplit(", ") |>
    unlist() |>
    unique()
  
  # Isolate other topics in both FR and DE
  id_other_topics <- grep("Andere|Autre", topics)
  main_topics <- topics[-id_other_topics]
  other_topics <- topics[id_other_topics]
  
  topics_to_diplay <- c(
    sort(
      main_topics
    ),
    # Other topics should appear last
    other_topics
  )
  return(topics_to_diplay)
}
