# WARNING - Generated by {fusen} from dev/flat_prepare_data_subfunctions.Rmd: do not edit by hand

#' Get the number of cantons influenced
#' 
#' @param data Tibble. Raw data about projects, with the good columns names.
#' 
#' @importFrom dplyr mutate
#' 
#' @return A tibble with a column with the number of cantons influenced
#' 
#' @noRd
#' @examples
#' # Import the raw data and perform the first preparations
#' raw_data <- import_raw_data() |> 
#'   add_col_raw_data() |> 
#'   clean_raw_data()
#'
#' # Get the number of cantons influenced
#' raw_data |> 
#'   get_nb_cantons_influenced() |> 
#'   select(geo_range, nb_cantons_influenced)
get_nb_cantons_influenced <- function(
    data
    ){
  
  data |> 
    mutate(
      nb_cantons_influenced = lengths(gregexpr(
          ",", 
          geo_range
        )
    ) + 1) 
  
}
