# WARNING - Generated by {fusen} from dev/flat_map.Rmd: do not edit by hand

#' Draw main interactive map
#'
#' @param projects_data_sf A sf data.frame containing coordinates of project 
#' main organisation and project `short_title`.
#' 
#' @param zoom_level An integer. The zoom level for the map. Defines
#' default zoom level.
#' 
#' @return A leaflet object.
#' 
#' @importFrom leaflet leaflet setView addProviderTiles leafletOptions setMaxBounds
#' 
#'
#' @noRd
#' @examples
#' draw_map_base() 
draw_map_base <- function(zoom_level = 8) {
  
  switzerland_centroid <- get_switzerland_centroid()
  switzerland_bounding_box <- get_switzerland_bounding_box()
  
  leaflet(
    options = leafletOptions(minZoom = zoom_level)
  ) |>
    addProviderTiles(
      provider = "CartoDB.Positron"
      ) |>
    setView(
      lng = switzerland_centroid[["lng"]],
      lat = switzerland_centroid[["lat"]],
      zoom = zoom_level
    ) |> 
    setMaxBounds(
      lng1 = switzerland_bounding_box[["xmin"]],
      lat1 = switzerland_bounding_box[["ymin"]],
      lng2 = switzerland_bounding_box[["xmax"]],
      lat2 = switzerland_bounding_box[["ymax"]]
    )
}

#' Draw map of selected projects
#' 
#' @param projects_data_sf A sf data.frame containing coordinates of project 
#' main organisation and project `short_title`.
#' 
#' @return A leaflet object.
#' 
#' @importFrom leaflet addCircleMarkers  addPolygons
#' 
#'
#' @noRd 
#' @examples
#' # Modify dummy_project_data_sf() to include target cantons
#' draw_map_focus_one_project(
#'   projects_data_sf = dummy_project_data_sf()
#' )
draw_map_focus_one_project <- function(
    projects_data_sf
){

  cantons_sf <- read_cantons_sf()
  
  # Extract target cantons from project_data_sf
  # Add column target_cantons (TRUE/FALSE) in project_data_sf
  
  draw_map_base()
  
  # Display target cantons in psch orange / others psch blue
  # Display selected project in psch orange
  
  # Nice to have
  # Display lines radiating from project to centroid of target cantons
  
}

#' Draw map of selected projects
#' 
#' @param projects_data_sf A sf data.frame containing coordinates of project 
#' main organisation and project `short_title`.
#' 
#' @return A leaflet object.
#' 
#' @importFrom leaflet addCircleMarkers  addPolygons
#' 
#'
#' @noRd 
#' @examples
#' draw_map_selected_projects(
#'   projects_data_sf = dummy_project_data_sf()
#' )
draw_map_selected_projects <- function(
    projects_data_sf
){
  draw_map_base() |> 
    addPolygons(
      data = read_cantons_sf(),
      weight = 1,
      color = psch_blue(),
      fillColor = psch_blue(),
      fillOpacity = 0.3
    ) |>
    addCircleMarkers(
      data = projects_data_sf,
      color = psch_orange(),
      stroke = FALSE,
      fillOpacity = 0.8,
      label = ~ as.character(short_title)
    )
}
