# WARNING - Generated by {fusen} from dev/flat_plot_budget.Rmd: do not edit by hand

#' Plot the distribution of the budgets
#' 
#' @param id Character. Id of the container in the DOM.
#' @param data_repart Tibble. Data to be plotted.
#' @param plot_options List. List of options for the plot.
#' @param session Session object.
#' 
#' @importFrom purrr pmap set_names
#' @importFrom dplyr mutate
#' 
#' @return A Java Script plot
#' 
#' @export
#' @examples
#' toy_data_repart <- tibble::tibble(
#'   name = c("Item 1", "Item 2"),
#'   value = c(75, 25), 
#'   value_tooltip = c("75 000 CHF", "25 000 CHF")
#' )
#'
#' # plot_contrib_budget_highcharter(
#' #   id = "id-in-the-dom-maybe-with-ns",
#' #   data_repart = toy_data_repart,
#' #   session = session
#' # )
plot_contrib_budget_highcharter <- function(
    id,
    data_repart,
    plot_options = list(
      axis_max = 100,
      axis_interval = 20,
      series_name = "",
      prefixer = "%"
    ),
    session
){
  
  # Transform the data in the right format
  data_to_compare <- pmap(
    list(
      data_repart$name, 
      data_repart$value, 
      data_repart$value_tooltip
    ), 
    ~ list(
      name = ..1, 
      value = ..2, 
      value_tooltip = ..3
    )
  ) |> 
    set_names(
      paste0(
        "place", 
        seq(from = 1, to = nrow(data_repart), by = 1)
      )
    )
  
  data <- list(
    id = id,
    plot_options = plot_options,
    data_to_compare = data_to_compare
  )
  
  # Transform the data in the right format
  session$sendCustomMessage(
    type = "createChart",
    message = list(
      data
    )
  )
  
}
