# WARNING - Generated by {fusen} from dev/flat_prepare_data.Rmd: do not edit by hand

#' Prepare the app data
#' 
#' @param name_raw_file Character. Name of the raw data file.
#' @param pkg_dir Character. Path to the package (must contain a data-raw folder).
#' @param dic_variables Tibble. Variables dictionaries. Mainly used for examples and unit testing purpose.
#' @param dic_cantons Tibble. Canton dictionary. Mainly used for examples and unit testing purpose.
#' @param dic_titles_pages Tibble. Title of the pages dictionaries. Mainly used for examples and unit testing purpose.
#' @param cantons_sf Sf data. Cantons geometry. Mainly used for examples and unit testing purpose.
#' 
#' @importFrom glue glue
#' @importFrom here here
#' @importFrom cli cli_process_start cli_alert cli_process_done
#' 
#' @return Nothing to return, used for side effect. A message is displayed in the console.
#' 
#' @export
#' @examples
#' # Load the toy datasets
#' data("toy_data_pgv")
#' data("toy_dic_variables")
#' data("toy_dic_cantons")
#' data("toy_dic_titles_pages")
#' data("toy_cantons_sf")
#'
#' # Create a temp folder with data-projects-raw and ata-projects subfolder
#' my_temp_dir <- tempfile("test-prepare-data")
#' dir.create(my_temp_dir)
#' dir.create(file.path(my_temp_dir, "data-projects-raw"))
#' dir.create(file.path(my_temp_dir, "data-projects"))
#' dir.create(file.path(my_temp_dir, "data-projects-cards"))
#'
#' # Save the toy PGV file inside
#' writexl::write_xlsx(
#'   toy_data_pgv, 
#'   file.path(
#'     my_temp_dir, 
#'     "data-projects-raw", 
#'     "toy_PGV.xlsx"
#'   )
#' )
#'
#' # Prepare the data
#' prepare_app_data(
#'   name_raw_file = "toy_PGV.xlsx",
#'   pkg_dir = my_temp_dir, 
#'   dic_variables = toy_dic_variables, 
#'   dic_cantons = toy_dic_cantons,
#'   dic_titles_pages = toy_dic_titles_pages,
#'   cantons_sf = toy_cantons_sf
#' )
#'
#' # Delete the tempdir
#' unlink(my_temp_dir, recursive = TRUE)
prepare_app_data <- function(
    name_raw_file = "PGV.xlsx",
    pkg_dir = system.file(package = "exploratorium"),
    dic_variables = NULL, 
    dic_cantons = NULL,
    dic_titles_pages = NULL,
    cantons_sf = NULL
  ){
  
  # Prepare the projects data
  projects_data <- prepare_projects_data(
    name_raw_file = name_raw_file,
    pkg_dir = pkg_dir,
    dic_variables = dic_variables,
    dic_cantons = dic_cantons,
    cantons_sf = cantons_sf
  )
  
  # Prepare the projects cards
  prepare_projects_cards(
    data_projects_fr = projects_data$data_fr,
    data_projects_de = projects_data$data_de,
    dic_titles_pages = dic_titles_pages,
    pkg_dir = pkg_dir
  )
  
  
}
