# WARNING - Generated by {fusen} from dev/flat_prepare_data_subfunctions.Rmd: do not edit by hand

#' Prepare the projects cards in DE and FR
#' 
#' @param id_project Character. ID of the project, 'short_title' in data.
#' @param data_projects Tibble. Data projects.
#' @param language Character. Language, 'fr' or 'de'.
#' @param dic_titles_pages Tibble. Title of the pages dictionaries. Mainly used for examples and unit testing purpose.
#' @param pkg_dir Character. Path to the package.
#' 
#' @importFrom htmltools htmlTemplate withTags
#' @importFrom glue glue
#' @importFrom purrr map set_names
#' @importFrom dplyr filter
#' @importFrom lubridate year
#' @importFrom scales number
#' 
#' @return Nothing. Used for side effects. Create the project card.
#' 
#' @noRd
#' @examples
#' # Create a temp folder with data-projects-cards subfolder
#' my_temp_dir <- tempfile("test-create-project-card")
#' dir.create(my_temp_dir)
#' dir.create(file.path(my_temp_dir, "data-projects-cards"))
#'   
#' file.copy(
#'   from = app_sys(
#'     "data-projects-cards", 
#'     "template_projects_cards.html"
#'     ), 
#'   to = file.path(
#'     my_temp_dir, 
#'     "data-projects-cards", 
#'     "template_projects_cards.html"
#'     )
#' )
#'
#' prepare_one_project_card(
#'   id_project = "1+1=3", 
#'   data_projects = read_projects_data(language = "de"),
#'   language = "de", 
#'   pkg_dir = my_temp_dir
#' )
#'
#' browseURL(
#'   file.path(
#'     my_temp_dir, 
#'     "data-projects-cards", 
#'     "project_card_113_de.html"
#'   )
#' )
#'
#' prepare_one_project_card(
#'   id_project = "1+1=3", 
#'   data_projects = read_projects_data(language = "fr"),
#'   language = "fr", 
#'   pkg_dir = my_temp_dir
#' )
#'
#' browseURL(
#'   file.path(
#'     my_temp_dir, 
#'     "data-projects-cards", 
#'     "project_card_113_fr.html"
#'   )
#' )
#'
#' unlink(my_temp_dir, recursive = TRUE)
prepare_one_project_card <- function(
    id_project,
    data_projects,
    language = c("de", "fr"),
    dic_titles_pages = NULL,
    pkg_dir = system.file(package = "exploratorium")
  ){
  
  language <- match.arg(language)
  
  # Check that the project exists in the raw data
  check_project_in_data <- id_project %in% data_projects[["short_title"]]
  
  if (isFALSE(check_project_in_data)) {
    stop(
      glue(
        "Project {id_project} is not found in {glue(\'projects_{language}.rds\')}",
        "Please check the data before to try again", 
        .sep = "\n")
    )
  }
  
  # Find the translations of the titles
  vec_id_titles_in_project_card <- c(
    "project_start_year_title",
    "project_project_manager_title", 
    "project_main_orga_title", 
    "project_advancement",
    "project_description_title", 
    "project_theme_title", 
    "project_risk_title", 
    "project_budget_title", 
    "project_prop_budget_title"
    )
  
  list_titles <- vec_id_titles_in_project_card |>
    map(
      ~ get_trad_title(
        title_id = .x,
        language = language, 
        dic_titles_pages = dic_titles_pages
      )
    ) |> 
    set_names(
      vec_id_titles_in_project_card
    )

  # Find the parameters about the project
  data_one_project <- data_projects |> 
    filter(short_title == id_project)
  
  short_title_value <- data_one_project[["short_title"]]
  status_value <- data_one_project[["status"]]
  
  if (language == "de") {
    possible_col_status <- c(
      "Abschluss" = psch_yellow(), 
      "Umsetzung" = psch_green(), 
      "Abbruch" = psch_bronce()
    )
  } else if (language == "fr") {
    possible_col_status <- c(
      "Termin\u00e9" = psch_yellow(), 
      "En cours" = psch_green(), 
      "Annul\u00e9" = psch_bronce()
    )
  }
  
  status_color <- possible_col_status[status_value]
  
  start_year_value <- year(data_one_project[["project_start"]])
  
  project_manager <- data_one_project[["project_support_gfch"]]
  project_manager_url <- 
    paste0(
      "https://promotionsante.ch/fondation/equipe?views_search_api_fulltext=",
      project_manager
    )
  project_manager_value <- glue(
    '<a href=\"{project_manager_url}\" target=\"_blank\">{project_manager}</a>'
  )
    
  main_orga_value <- data_one_project[["main_resp_orga"]]
  
  description_value <- data_one_project[[glue("desc_{language}")]]
  
  if (language == "de") {
    
    more_description_value <- 'Weitere informationen finden sie auf der <a href=\"https://gesundheitsfoerderung.ch/praevention-in-der-gesundheitsversorgung/projektfoerderung/gefoerderte-projekte\" target=\"_blank\">website von Gesundheitf\u00f6rdernung Schweiz</a>'
    
  } else if (language == "fr") {
    
    more_description_value <- 'Vous trouverez des informations compl\u00e9mentaires  sur le <a href=\"https://promotionsante.ch/prevention-dans-le-domaine-des-soins/soutien-de-projets/projets-soutenus\" target=\"_blank\">site de Promotion Sant\u00e9 Suisse</a>'
    
  }
  
  theme_value <- paste0(
    "<li>",
    gsub(
      pattern = ",*\r\n|, ", "</li><li>", 
      data_one_project[["topic"]]
    ),
    "</li>"
  )
  risk_value <- paste0(
    "<li>",
    gsub(
      pattern = ",*\r\n|, ", "</li><li>", 
      data_one_project[["risk_factors"]]
    ),
    "</li>"
  )
    
  budget_value <- number(
    as.numeric(data_one_project[["total_budget"]]), 
    suffix = " CHF"
  )
  
  # Generate the html content
  html_content <- htmlTemplate(
    filename = system.file(
      "data-projects-cards",
      "template_projects_cards.html",
      package = "exploratorium"
    ),
    short_title_value = short_title_value,
    status_color = status_color,
    status_value = status_value,
    project_start_year_title = list_titles[["project_start_year_title"]],
    project_project_manager_title = HTML(list_titles[["project_project_manager_title"]]),
    project_main_orga_title = list_titles[["project_main_orga_title"]],
    start_year_value = start_year_value,
    project_manager_value = HTML(project_manager_value),
    main_orga_value = main_orga_value,
    project_advancement = list_titles[["project_advancement"]],
    start_year = year(data_one_project$project_start),
    completion_percentage = compute_project_completion_percentage(
      date_project_start = data_one_project$project_start,
      date_project_end = data_one_project$project_end
    ),
    end_year = year(data_one_project$project_end),
    project_description_title = list_titles[["project_description_title"]],
    description_value = description_value,
    more_description_value = HTML(more_description_value),
    project_theme_title = list_titles[["project_theme_title"]],
    theme_value = HTML(theme_value),
    project_risk_title = list_titles[["project_risk_title"]],
    risk_value = HTML(risk_value),
    project_budget_title = list_titles[["project_budget_title"]],
    budget_value = budget_value,
    project_prop_budget_title = list_titles[["project_prop_budget_title"]]
  )
  
  # Save the html file
  clean_id_project <- clean_id_project(
    id_project = id_project
  )
  name_file <- glue("project_card_{clean_id_project}_{language}.html")
  
  file_con <- file.path(
      pkg_dir, 
      "data-projects-cards",
      name_file
    )
  
  writeLines(
    as.character(html_content), 
    file_con
  )

}
