# WARNING - Generated by {fusen} from dev/flat_prepare_data.Rmd: do not edit by hand

#' Prepare the projects data in FR and DE to be included in the app as .rds files
#' 
#' @param name_raw_file Character. Name of the raw data file.
#' @param pkg_dir Character. Path to the package (must contain a data-raw folder).
#' 
#' @importFrom glue glue
#' @importFrom here here
#' 
#' @return Nothing to return, used for side effect. A message is displayed in the console.
#' 
#' @export
#' @examples
#' prepare_projects_data()
prepare_projects_data <- function(
    name_raw_file = "PGV.xlsx",
    pkg_dir = system.file(package = "observatoire")
  ){
  
  # Prepare the data and save them
  import_raw_data(
    name_raw_file = name_raw_file,
    pkg_dir = pkg_dir
  ) |> 
  add_col_raw_data() |> 
  clean_raw_data() |>
  get_coord_main_resp_orga() |>
  get_canton_main_resp_orga() |> 
  get_nb_cantons_influenced() |> 
  get_prop_budget() |> 
  translate_values_in_data() |> 
  save_projects_data(
    pkg_dir = pkg_dir
  )
 
}
