# WARNING - Generated by {fusen} from dev/flat_prepare_data_subfunctions.Rmd: do not edit by hand

#' Prepare all the project cards in DE and FR
#' 
#' @param data_projects_fr Tibble. Projects data in FR.
#' @param data_projects_de Tibble. Projects data in DE.
#' @param dic_titles_pages Tibble. Title of the pages dictionaries. Mainly used for examples and unit testing purpose.
#' @param pkg_dir Character. Path to the package.
#' 
#' @importFrom dplyr pull
#' @importFrom purrr walk
#' @importFrom glue glue
#' @importFrom cli cli_process_start cli_process_done
#' 
#' @return Nothing. Used for side effects. Create the project card.
#' @noRd
#' @examples
#' # Load the toy datasets
#' data("toy_projects_data_sf")
#' data("toy_dic_titles_pages")
#'
#' # Keep 2 projects
#' toy_data <- toy_projects_data_sf[1:2, ]
#'
#' # Create a temp folder with data-projects-cards subfolder
#' my_temp_dir <- tempfile("test-create-project-card")
#' dir.create(my_temp_dir)
#' dir.create(file.path(my_temp_dir, "data-projects-cards"))
#'   
#' file.copy(
#'   from = system.file(
#'     "data-projects-cards", 
#'     "template_projects_cards.html", 
#'     package = "observatoire"
#'     ), 
#'   to = file.path(
#'     my_temp_dir, 
#'     "data-projects-cards", 
#'     "template_projects_cards.html"
#'     )
#' )
#'   
#' prepare_projects_cards(
#'   data_projects_fr = toy_data,
#'   data_projects_de = toy_data,
#'   dic_titles_pages = toy_dic_titles_pages,
#'   pkg_dir = my_temp_dir
#' )
#'
#' list.files(
#'   file.path(
#'     my_temp_dir, 
#'     "data-projects-cards"
#'   )
#' )
#'
#' unlink(my_temp_dir, recursive = TRUE)
prepare_projects_cards <- function(
    data_projects_fr = read_projects_data(language = "fr"),
    data_projects_de = read_projects_data(language = "de"),
    dic_titles_pages = NULL,
    pkg_dir = system.file(package = "observatoire")
    ){
  
  cli_process_start(
    "Start to prepare the projects cards"
  )
  
  # Clean everything
  files_in_dir <- list.files(
    file.path(
      pkg_dir, 
      "data-projects-cards"
    )
  )
  files_to_delete <- files_in_dir[
    !(files_in_dir %in% c("projects_cards.css", "template_projects_cards.html"))
  ]
  files_to_delete |> 
    walk(
      ~ unlink(
        file.path(
          pkg_dir, 
          "data-projects-cards", 
          .x
        )
      )
    )
  
  # Get all the id of the projects
  all_id_projects <- data_projects_fr |> pull(short_title)
  
  # Create all cards in FR
  all_id_projects |> 
    walk(
      ~ prepare_one_project_card(
          id_project = .x, 
          language = "fr", 
          data_projects = data_projects_fr,
          dic_titles_pages = dic_titles_pages,
          pkg_dir = pkg_dir
      )
    )
  
  # Create all cards in DE
  all_id_projects |> 
    walk(
      ~ prepare_one_project_card(
          id_project = .x, 
          language = "de", 
          data_projects = data_projects_de,
          dic_titles_pages = dic_titles_pages,
          pkg_dir = pkg_dir
      )
    )
  
  # Print a message about the time of modification
  available_files_in_data <- list.files(
    file.path(
      pkg_dir, 
      "data-projects-cards"
    )
  )
  
  nb_files_fr <- length(grep(
    pattern = "_fr.html", 
    x = available_files_in_data
  ))
  
  nb_files_de <- length(grep(
    pattern = "_de.html", 
    x = available_files_in_data
  ))
  
  if (nb_files_fr != 0 & nb_files_de != 0) {
    
    time_modif <- file.info(
      file.path(
        pkg_dir, 
        'data-projects-cards', 
        available_files_in_data[1]))$mtime
    
    message(
      glue(
        "{nb_files_de} projects cards in DE have been updated at {time_modif}",
        "{nb_files_fr} projects cards in FR have been updated at {time_modif}", 
        .sep = "\n"
        )
      )
    
  } else {
    
    stop(
      "Something went wrong about the preparation of the projects cards"
    )
    
  }
  
  cli_process_done(
    "Finish to prepare the projects cards"
  )
    
}
