# WARNING - Generated by {fusen} from dev/flat_prepare_data_subfunctions.Rmd: do not edit by hand

#' Prepare all the project cards in DE and FR
#' 
#' @param data_projects_fr Tibble. Projects data in FR.
#' @param data_projects_de Tibble. Projects data in DE.
#' @param pkg_dir Character. Path to the package.
#' 
#' @importFrom dplyr pull
#' @importFrom purrr walk
#' 
#' @return Nothing. Used for side effects. Create the project card.
#' 
#' @export
#' @examples
#' # Load the toy datasets
#' data("toy_projects_data_sf")
#'
#' # Keep 2 projects
#' toy_data <- toy_projects_data_sf[1:2, ]
#'
#' # Create a temp folder with data-projects-cards subfolder
#' my_temp_dir <- tempfile("test-create-project-card")
#' dir.create(my_temp_dir)
#' dir.create(file.path(my_temp_dir, "data-projects-cards"))
#'   
#' file.copy(
#'   from = system.file(
#'     "data-projects-cards", 
#'     "template_projects_cards.html", 
#'     package = "observatoire"
#'     ), 
#'   to = file.path(
#'     my_temp_dir, 
#'     "data-projects-cards", 
#'     "template_projects_cards.html"
#'     )
#' )
#'   
#' prepare_projects_cards(
#'   data_projects_fr = toy_data,
#'   data_projects_de = toy_data,
#'   pkg_dir = my_temp_dir
#' )
#'
#' list.files(
#'   file.path(
#'     my_temp_dir, 
#'     "data-projects-cards"
#'   )
#' )
#'
#' unlink(my_temp_dir, recursive = TRUE)
prepare_projects_cards <- function(
    data_projects_fr = read_projects_data(language = "fr"),
    data_projects_de = read_projects_data(language = "de"),
    pkg_dir = system.file(package = "observatoire")
    ){
  
  # Clean everything
  files_in_dir <- list.files(
    file.path(
      pkg_dir, 
      "data-projects-cards"
    )
  )
  files_to_delete <- files_in_dir[
    !(files_in_dir %in% c("projects_cards.css", "template_projects_cards.html"))
  ]
  files_to_delete |> 
    walk(
      ~ unlink(
        file.path(
          pkg_dir, 
          "data-projects-cards", 
          .x
        )
      )
    )
  
  # Get all the id of the projects
  all_id_projects <- data_projects_fr |> pull(short_title)
  
  # Create all cards in FR
  all_id_projects |> 
    walk(
      ~ prepare_one_project_card(
          id_project = .x, 
          language = "fr", 
          data_projects = data_projects_fr,
          pkg_dir = pkg_dir
      )
    )
  
  # Create all cards in DE
  all_id_projects |> 
    walk(
      ~ prepare_one_project_card(
          id_project = .x, 
          language = "de", 
          data_projects = data_projects_de,
          pkg_dir = pkg_dir
      )
    )
    
}
