# WARNING - Generated by {fusen} from dev/flat_prepare_data_subfunctions.Rmd: do not edit by hand

#' Translate the data (values in the table) in FR and DE
#' 
#' @param data Tibble. Raw data about projects, with the good columns names.
#' 
#' @return A list of 2 tibbles (FR and DE)
#' 
#' @noRd
#' @examples
#' # Import the raw data and perform the first preparations
#' raw_data <- import_raw_data() |> 
#'   add_col_raw_data() |> 
#'   clean_raw_data()
#'
#' # Get the translated data in FR and DE
#' raw_data |> 
#'   translate_values_in_data()
translate_values_in_data <- function(
    data
    ){
  
  #TODO
  list(
    data_fr = data, 
    data_de = data
  )
    
}
