on: [push]

name: check

jobs:
  check:
    runs-on: ubuntu-latest
    container: rocker/geospatial:4.3.2
    steps:
      - uses: actions/checkout@v4

      - name: Set repos option to match thinkr dev env
        run: bash dev/ci/set_repos_option_to_match_thinkr_dev_env.sh

      - name: Install application dependencies
        run: |
          install.packages("pak")
          pak::local_install(upgrade = FALSE, dependencies = TRUE)
          rcmdcheck::rcmdcheck(args = c("--no-manual"), error_on = "warning", check_dir = "check")
        shell: Rscript {0}

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: check-r-results
          path: check