on:
  push:
    branches: [main, uat, production, test-ci]

name: deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: rocker/geospatial:4.3.2
    steps:
      - uses: actions/checkout@v4
      
      - name: Set repos option to match thinkr dev env
        run: bash dev/ci/set_repos_option_to_match_thinkr_dev_env.sh

      - name: Install application dependencies
        run: |
          install.packages("pak")
          pak::local_install(upgrade = FALSE, dependencies = TRUE)
        shell: Rscript {0}

      - name: Deploy application
        env:
          SHINYAPPS_IO_NAME: ${{ vars.SHINYAPPS_IO_NAME }}
          SHINYAPPS_IO_TOKEN: ${{ secrets.SHINYAPPS_IO_TOKEN }}
          SHINYAPPS_IO_SECRET: ${{ secrets.SHINYAPPS_IO_SECRET }}
        run: Rscript dev/ci/deploy_app.R


      
